question_list = {
    "dictionary": [["<ruby>辞書<rt>じしょ</rt></ruby>",
    "Use the dictionary to look up new English words."], "https://storage.googleapis.com/eiken5/2024_12_24_13_37_31_1.mp3"],
    "fever": [["<ruby>熱<rt>ねつ</rt></ruby>",
    "I always get a high (         ) when I have influenza."], "https://storage.googleapis.com/eiken5/2024_12_24_14_05_54_1.mp3"],
    "go": [["<ruby>行<rt>い</rt></ruby>く",
    "I will (         ) to Sweden next year."], "https://storage.googleapis.com/eiken5/2024_12_24_14_14_57_1.mp3"],
    "race": [["レース",
    "I saw a super fast (         ) car yesterday."], "https://storage.googleapis.com/eiken5/2025_01_07_01_40_14_1.mp3"],
    "rock": [["<ruby>岩<rt>いわ</rt></ruby>",
    "I found a (         ) yesterday that looked like a diamond."], "https://storage.googleapis.com/eiken5/2025_01_07_01_58_33_1.mp3"],
    "weak": [["<ruby>弱<rt>よわ</rt></ruby>い",
    "He has small muscles. He is (         )."], "https://storage.googleapis.com/eiken5/2025_01_07_02_45_14_1.mp3"],
    "drive": [["<ruby>運転<rt>うんてん</rt></ruby>する",
    "I will (         ) my car to work tomorrow."], "https://storage.googleapis.com/eiken5/2024_12_24_13_38_56_1.mp3"],
    "wish": [["<ruby>願<rt>ねが</rt></ruby>う、<ruby>願<rt>ねが</rt></ruby>い",
    "I (         ) you good luck."], "https://storage.googleapis.com/eiken5/2025_01_07_02_57_22_1.mp3"],
    "alone": [["<ruby>一人<rt>ひとり</rt></ruby>で",
    "She likes to study (        ) in her room."], "https://storage.googleapis.com/eiken3sound1/2025_06_03_11_53_21_1.mp3"],
    "belong": [["<ruby>所属<rt>しょぞく</rt></ruby>する",
    "Does this book (        ) to you?"], "https://storage.googleapis.com/eiken3sound1/2025_06_03_12_02_07_1.mp3"],
    "choice": [["<ruby>選択<rt>せんたく</rt></ruby>",
    "You have a (        ) between two different colors."], "https://storage.googleapis.com/eiken3sound1/2025_06_03_12_08_10_1.mp3"],
    "connect": [["つなぐ",
    "You can (        ) to the internet using Wi-Fi."], "https://storage.googleapis.com/eiken3sound1/2025_06_03_12_09_33_1.mp3"],
    "disease": [["<ruby>病気<rt>びょうき</rt></ruby>",
    "The doctor is researching a new treatment for the (        )."], "https://storage.googleapis.com/eiken3sound1/2025_06_03_12_23_03_1.mp3"],
    "document": [["<ruby>書類<rt>しょるい</rt></ruby>",
    "Please sign this (        ) and return it."], "https://storage.googleapis.com/eiken3sound1/2025_06_03_12_23_18_1.mp3"],
    "emotion": [["<ruby>感情<rt>かんじょう</rt></ruby>",
    "Happiness is a strong (        )."], "https://storage.googleapis.com/eiken3sound1/2025_06_04_10_10_42_1.mp3"],
    "exhibition": [["<ruby>展示<rt>てんじ</rt></ruby>",
    "We visited an art (        ) at the gallery."], "https://storage.googleapis.com/eiken3sound1/2025_06_04_10_14_20_1.mp3"],
    "imagine": [["<ruby>想像<rt>そうぞう</rt></ruby>する",
    "Can you (        ) a world without cars?"], "https://storage.googleapis.com/eiken3sound1/2025_06_04_13_08_44_1.mp3"],
    "lift": [["<ruby>持<rt>も</rt></ruby>ち<ruby>上<rt>あ</rt></ruby>げる",
    "Can you help me (        ) this heavy box?"], "https://storage.googleapis.com/eiken3sound1/2025_06_04_13_40_21_1.mp3"],
    "mask": [["マスク",
    "Wear a (        ) to protect yourself from dust."], "https://storage.googleapis.com/eiken3sound2/2025_06_04_14_55_47_1.mp3"],
    "muscle": [["<ruby>筋肉<rt>きんにく</rt></ruby>",
    "Regular exercise helps build strong (        )s."], "https://storage.googleapis.com/eiken3sound2/2025_06_04_15_07_32_1.mp3"],
    "quality": [["<ruby>質<rt>しつ</rt></ruby>",
    "This store sells products of high (        ). They are pretty expensive."], "https://storage.googleapis.com/eiken3sound2/2025_06_04_15_33_54_1.mp3"],
    "shrink": [["<ruby>縮<rt>ちぢ</rt></ruby>む",
    "My wool sweater will (        ) if I wash it in hot water."], "https://storage.googleapis.com/eiken3sound2/2025_06_05_10_43_19_1.mp3"],
    "various": [["<ruby>様々<rt>さまざま</rt></ruby>な",
    "There are (        ) reasons for her decision."], "https://storage.googleapis.com/eiken3sound2/2025_06_05_12_06_40_1.mp3"],
    "band": [["バンド、<ruby>帯<rt>おび</rt></ruby>",
    "My favorite (        ) is playing at a concert next month."], "https://storage.googleapis.com/eiken_pre2_sound1/2025_06_28_19_54_09_2.mp3"],
    "sale": [["<ruby>販売<rt>はんばい</rt></ruby>",
    "The store is having a big (        ) this weekend."], "https://storage.googleapis.com/eiken_pre2_sound2/2025_06_30_13_04_56_2.mp3"],
    "come true": [["<ruby>叶<rt>かな</rt></ruby>う",
    "Her dream will (         ) someday."], "https://storage.googleapis.com/real_eiken3/2025_07_26_14_55_33_2.mp3"],
    "take part in": [["〜に<ruby>参加<rt>さんか</rt></ruby>する",
    "Many students (         ) school events."], "https://storage.googleapis.com/real_eiken3/2025_07_26_14_59_10_2.mp3"],
    "simple": [["<ruby>簡単<rt>かんたん</rt></ruby>な",
    "The test was very (         ). Everyone passed it."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_16_27_2.mp3"],
    "abroad": [["<ruby>外国<rt>がいこく</rt></ruby>へ、<ruby>外国<rt>がいこく</rt></ruby>で",
    "She studied (         ) last year."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_19_31_2.mp3"],
    "belong to": [["〜に<ruby>所属<rt>しょぞく</rt></ruby>している",
    "They (         ) the tennis club."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_19_55_2.mp3"],
    "several": [["いくつかの、<ruby>数個<rt>すうこ</rt></ruby>の",
    "He bought (         ) books. He reads many books every day."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_20_13_2.mp3"],
    "control": [["<ruby>管理<rt>かんり</rt></ruby>する、<ruby>制御<rt>せいぎょ</rt></ruby>する",
    "He can (         ) the machine with the remote."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_31_09_2.mp3"],
    "shake hands with": [["〜と<ruby>握手<rt>あくしゅ</rt></ruby>する",
    "I want to (         ) the singer. She’s my favorite star."], "https://storage.googleapis.com/real_eiken3/2025_07_26_15_57_10_2.mp3"],
    "patient": [["<ruby>患者<rt>かんじゃ</rt></ruby>、<ruby>我慢強<rt>がまんづよ</rt></ruby>い、<ruby>辛抱強<rt>しんぼうづよ</rt></ruby>い",
    "The doctor listened carefully to his (        )."], "https://storage.googleapis.com/eiken_pre2_sound2/2025_06_30_12_32_12_2.mp3"],
    "anywhere": [["どこでも",
    "You can sit (         ) you like in this room."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_28_01_18_58_2.mp3"],
    "including": [["〜を<ruby>含<rt>ふく</rt></ruby>めて",
    "Five people, (         ) me, joined the trip."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_28_01_19_51_2.mp3"],
    "shake": [["<ruby>振<rt>ふ</rt></ruby>る／<ruby>揺<rt>ゆ</rt></ruby>れる",
    "(         ) the bottle before drinking it to make sure the juice is well mixed."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_28_01_27_55_2.mp3"],
    "even if": [["たとえ〜でも",
    "(         ) it rains, we will still have the picnic. We won’t cancel our plans."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_28_01_29_09_2.mp3"],
    "probably": [["<ruby>多分<rt>たぶん</rt></ruby>",
    "She will (         ) come to the party. She said she was free tonight."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_28_02_07_14_2.mp3"],
    "imagination": [["<ruby>想像力<rt>そうぞうりょく</rt></ruby>",
    "Reading books helps develop your (         )."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_29_02_50_28_2.mp3"],
    "get along with": [["<ruby>仲良<rt>なかよ</rt></ruby>くする",
    "She doesn’t (         ) her new classmates. It’s been hard for her."], "https://storage.googleapis.com/real_eiken_pre2_sound1/2025_07_29_03_02_38_2.mp3"],
    "no longer": [["もはや〜ない",
    "She (         ) lives here, so the house is empty. It feels strange to see it like that."], "https://storage.googleapis.com/real_eiken_pre2_sound2/2025_07_29_19_07_14_2.mp3"],
    "item": [["<ruby>品物<rt>しなもの</rt></ruby>、<ruby>項目<rt>こうもく</rt></ruby>",
    "This (         ) is out of stock. We’ll get more next week."], "https://storage.googleapis.com/real_eiken_pre2_sound2/2025_07_30_02_33_37_2.mp3"],
    "on sale": [["セール中",
    "These shoes are (         ) this week. You can get them cheap."], "https://storage.googleapis.com/real_eiken_pre2_sound2/2025_07_30_02_55_54_2.mp3"],
    "against": [["〜に<ruby>反対<rt>はんたい</rt></ruby>して、〜に<ruby>対<rt>たい</rt></ruby>して",
    "He is strongly (         ) the idea of cutting down more trees."], "https://storage.googleapis.com/real_eiken_pre2_sound2/2025_07_30_03_06_09_2.mp3"],
    "inventor": [["<ruby>発明家<rt>はつめいか</rt></ruby>",
    "Thomas Edison was a famous (         ). He created the light bulb and many other things we use today."], "https://storage.googleapis.com/eiken2_sounds/2025_08_02_07_43_48_2.mp3"],
    "access": [["アクセス",
    "Students can (         ) the library website from home. It’s very convenient. "], "https://storage.googleapis.com/eiken2_sounds2/2025_08_02_22_16_36_2.mp3"],
    "certainly": [["<ruby>確<rt>たし</rt></ruby>かに",
    "I will (        ) help you if I can."], "https://storage.googleapis.com/eiken_pre2_sound1/2025_06_28_19_56_48_2.mp3"],
    "rather": [["むしろ",
    "It's (        ) cold for this time of year."], "https://storage.googleapis.com/eiken_pre2_sound2/2025_06_30_12_47_06_2.mp3"],
    "vacuum": [["<ruby>真空<rt>しんくう</rt></ruby>",
    "There's a complete (        ) in space."], "https://storage.googleapis.com/eiken_pre2_sound2/2025_06_30_13_47_11_2.mp3"],
}
