question_list = {
    "take a class": [["",
    ""], ""],
    "instant": [["",
    ""], ""],
    "itroduction": [["",
    ""], ""],
    "I wish I could": [["",
    ""], ""],
    "powerful": [["",
    ""], ""],
    "ball game": [["",
    ""], ""],
    "not good but okay": [["",
    ""], ""],
    "musical": [["",
    ""], ""],
    "knew": [["",
    ""], ""],
    "if you had": [["",
    ""], ""],
    "what's more": [["",
    ""], ""],
    "would": [["",
    ""], ""],
    "society": [["",
    ""], ""],
    "grandchildren": [["",
    ""], ""],
    "announcement": [["",
    ""], ""],
    "vocalist": [["",
    ""], ""],
    "miss out on": [["",
    ""], ""],
    "heater": [["",
    ""], ""],
    "inter-class": [["",
    ""], ""],
    "wouldn't": [["",
    ""], ""],
    "password": [["",
    ""], ""],
    "AI": [["",
    ""], ""],
    "grand opening": [["",
    ""], ""],
    "loneliness": [["",
    ""], ""],
    "go with": [["",
    ""], ""],
    "trash can": [["",
    ""], ""],
    "tornament": [["",
    ""], ""],
    "compact": [["",
    ""], ""],
    "far away": [["",
    ""], ""],
    "itself": [["",
    ""], ""],
}
