import pykakasi

kks = pykakasi.kakasi()
raw_eiken4_vocab = {
    'another': ['別の', 'https://storage.googleapis.com/eiken5/2025_03_15_18_19_34_1.mp3'],
    'around': ['周りに', 'https://storage.googleapis.com/eiken5/2025_03_15_18_19_38_1.mp3'],
    'able': ['できる', 'https://storage.googleapis.com/eiken5/2025_03_15_18_19_42_1.mp3'],
    'adult': ['大人', 'https://storage.googleapis.com/eiken5/2024_12_18_14_02_49_1.mp3'],
    'airport': ['空港', 'https://storage.googleapis.com/eiken5/2024_12_18_14_31_55_1.mp3'],
    'album': ['アルバム', 'https://storage.googleapis.com/eiken5/2024_12_18_14_31_58_1.mp3'],
    'art': ['芸術、美術', 'https://storage.googleapis.com/eiken5/2024_12_18_14_32_32_1.mp3'],
    'apartment': ['アパート', 'https://storage.googleapis.com/eiken5/2024_12_17_14_48_58_1.mp3'],
    'artist': ['アーティスト', 'https://storage.googleapis.com/eiken5/2024_12_18_14_32_36_1.mp3'],
    'begin': ['始める', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_05_1.mp3'],
    'behind': ['後ろ', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_08_1.mp3'],
    'bell': ['ベル、鐘', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_11_1.mp3'],
    'below': ['下', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_14_1.mp3'],
    'beside': ['そばに', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_18_1.mp3'],
    'become': ['なる', 'https://storage.googleapis.com/eiken5/2024_12_24_12_59_50_1.mp3'],
    'best': ['最高', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_20_1.mp3'],
    'better': ['より良い', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_24_1.mp3'],
    'between': ['間', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_27_1.mp3'],
    'birthday': ['誕生日', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_37_1.mp3'],
    'black': ['黒い', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_41_1.mp3'],
    'blanket': ['毛布', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_44_1.mp3'],
    'block': ['ブロック', 'https://storage.googleapis.com/eiken5/2024_12_24_13_00_48_1.mp3'],
    'body': ['体', 'https://storage.googleapis.com/eiken5/2024_12_24_13_01_01_1.mp3'],
    'bone': ['骨', 'https://storage.googleapis.com/eiken5/2024_12_24_13_01_06_1.mp3'],
    'bridge': ['橋', 'https://storage.googleapis.com/eiken5/2024_12_24_13_01_59_1.mp3'],
    'bring': ['持ってくる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_02_02_1.mp3'],
    'build': ['建てる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_17_03_1.mp3'],
    'building': ['建物', 'https://storage.googleapis.com/eiken5/2024_12_24_13_17_07_1.mp3'],
    'candle': ['ろうそく', 'https://storage.googleapis.com/eiken5/2024_12_24_13_17_42_1.mp3'],
    'catch': ['捕まえる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_11_1.mp3'],
    'cause': ['原因', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_15_1.mp3'],
    'ceiling': ['天井', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_18_1.mp3'],
    'cell phone': ['携帯電話', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_21_1.mp3'],
    'cent': ['セント', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_27_1.mp3'],
    'center': ['中心', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_32_1.mp3'],
    'certain': ['確か、間違えない', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_35_1.mp3'],
    'chalk': ['チョーク', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_43_1.mp3'],
    'chance': ['機会', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_46_1.mp3'],
    'change': ['変える', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_50_1.mp3'],
    'check': ['検査', 'https://storage.googleapis.com/eiken5/2024_12_24_13_18_56_1.mp3'],
    'careful': ['注意深い', 'https://storage.googleapis.com/eiken5/2024_12_24_13_17_56_1.mp3'],
    'cheer': ['こぶする', 'https://storage.googleapis.com/eiken5/2024_12_24_13_19_00_1.mp3'],
    'cigarette': ['タバコ', 'https://storage.googleapis.com/eiken5/2024_12_24_13_28_57_1.mp3'],
    'climb': ['登る', 'https://storage.googleapis.com/eiken5/2024_12_24_13_29_35_1.mp3'],
    'clerk': ['店員', 'https://storage.googleapis.com/eiken5/2024_12_24_13_29_23_1.mp3'],
    'compare': ['比べる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_30_48_1.mp3'],
    'complain': ['文句', 'https://storage.googleapis.com/eiken5/2024_12_24_13_30_51_1.mp3'],
    'complete': ['完成する', 'https://storage.googleapis.com/eiken5/2024_12_24_13_30_55_1.mp3'],
    'concentrate': ['集中する', 'https://storage.googleapis.com/eiken5/2024_12_24_13_31_04_1.mp3'],
    'dead': ['死んでいる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_36_55_1.mp3'],
    'dear': ['親愛なる', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_02_1.mp3'],
    'deep': ['深い', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_08_1.mp3'],
    'dentist': ['歯医者', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_16_1.mp3'],
    'department': ['部門', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_19_1.mp3'],
    'desert': ['砂漠', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_23_1.mp3'],
    'direction': ['方向', 'https://storage.googleapis.com/eiken5/2024_12_24_13_37_47_1.mp3'],
    'double': ['二倍', 'https://storage.googleapis.com/eiken5/2024_12_24_13_38_35_1.mp3'],
    'draw': ['描く', 'https://storage.googleapis.com/eiken5/2024_12_24_13_38_44_1.mp3'],
    'drive': ['運転する', 'https://storage.googleapis.com/eiken5/2024_12_24_13_38_56_1.mp3'],
    'dust': ['ほこり', 'https://storage.googleapis.com/eiken5/2024_12_24_13_39_18_1.mp3'],
    'duty': ['義務', 'https://storage.googleapis.com/eiken5/2024_12_24_13_39_23_1.mp3'],
    'eagle': ['鷲', 'https://storage.googleapis.com/eiken5/2024_12_24_13_39_27_1.mp3'],
    'environment': ['環境', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_56_1.mp3'],
    'equal': ['等しい', 'https://storage.googleapis.com/eiken5/2024_12_24_13_50_06_1.mp3'],
    'engine': ['エンジン', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_33_1.mp3'],
    'engineer': ['エンジニア', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_37_1.mp3'],
    'english': ['英語', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_42_1.mp3'],
    'enough': ['十分', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_45_1.mp3'],
    'enter': ['入る', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_49_1.mp3'],
    'envelope': ['封筒', 'https://storage.googleapis.com/eiken5/2024_12_24_13_49_52_1.mp3'],
    'excited': ['わくわく', 'https://storage.googleapis.com/eiken5/2024_12_18_13_59_00_1.mp3'],
    'entrance': ['入口', 'https://storage.googleapis.com/eiken5/2024_12_18_09_23_47_1.mp3'],
    'fact': ['事実', 'https://storage.googleapis.com/eiken5/2024_12_24_13_52_29_1.mp3'],
    'factory': ['工場', 'https://storage.googleapis.com/eiken5/2024_12_24_13_52_32_1.mp3'],
    'fail': ['失敗する', 'https://storage.googleapis.com/eiken5/2024_12_24_13_52_36_1.mp3'],
    'fear': ['恐れ', 'https://storage.googleapis.com/eiken5/2024_12_24_14_05_37_1.mp3'],
    'field': ['畑', 'https://storage.googleapis.com/eiken5/2024_12_24_14_06_01_1.mp3'],
    "fight": ["戦う", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_16_1.mp3"],
    "fill": ["満たす", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_20_1.mp3"],
    "final": ["最終", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_24_1.mp3"],
    "find": ["見つける", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_28_1.mp3"],
    "fine": ["良い", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_31_1.mp3"],
    "finger": ["指", "https://storage.googleapis.com/eiken5/2024_12_24_14_06_51_1.mp3"],
    "finish": ["終わる", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_04_1.mp3"],
    "fire": ["火", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_08_1.mp3"],
    "first": ["最初", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_11_1.mp3"],
    "fix": ["直す", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_24_1.mp3"],
    "flash": ["光", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_32_1.mp3"],
    "flat": ["平たい", "https://storage.googleapis.com/eiken5/2024_12_24_14_07_35_1.mp3"],
    "forget": ["忘れる", "https://storage.googleapis.com/eiken5/2024_12_24_14_13_33_1.mp3"],
    "forgive": ["許す", "https://storage.googleapis.com/eiken5/2024_12_24_14_13_37_1.mp3"],
    "friendly": ["人懐っこい、フレンドリー", "https://storage.googleapis.com/eiken5/2024_12_24_14_13_42_1.mp3"],
    "future": ["未来", "https://storage.googleapis.com/eiken5/2024_12_24_14_14_08_1.mp3"],
    "geography": ["地理", "https://storage.googleapis.com/eiken5/2024_12_24_14_14_22_1.mp3"],
    "get": ["貰う", "https://storage.googleapis.com/eiken5/2024_12_24_14_14_26_1.mp3"],
    "giant": ["巨人", "https://storage.googleapis.com/eiken5/2024_12_24_14_14_30_1.mp3"],
    "gift": ["プレゼント", "https://storage.googleapis.com/eiken5/2024_12_24_14_14_34_1.mp3"],
    "grade": ["学年、成績、程度", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_25_1.mp3"],
    "grandfather": ["祖父", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_29_1.mp3"],
    "grandmother": ["祖母", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_32_1.mp3"],
    "grass": ["草", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_35_1.mp3"],
    "gray": ["灰色", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_39_1.mp3"],
    "great": ["凄い", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_42_1.mp3"],
    "green": ["緑", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_46_1.mp3"],
    "group": ["グループ", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_49_1.mp3"],
    "grow": ["育つ", "https://storage.googleapis.com/eiken5/2024_12_24_14_15_52_1.mp3"],
    "guest": ["ゲスト", "https://storage.googleapis.com/eiken5/2024_12_24_14_22_13_1.mp3"],
    "guide": ["ガイド", "https://storage.googleapis.com/eiken5/2024_12_24_14_22_16_1.mp3"],
    "guitar": ["ギター", "https://storage.googleapis.com/eiken5/2024_12_24_14_22_19_1.mp3"],
    "help": ["助ける", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_37_1.mp3"],
    "here": ["ここ", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_39_1.mp3"],
    "hero": ["ヒーロー", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_42_1.mp3"],
    "high": ["高い", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_46_1.mp3"],
    "hill": ["丘", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_50_1.mp3"],
    "history": ["歴史", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_52_1.mp3"],
    "hobby": ["趣味", "https://storage.googleapis.com/eiken5/2024_12_24_14_23_58_1.mp3"],
    "holiday": ["休日", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_02_1.mp3"],
    "hope": ["望む", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_07_1.mp3"],
    "hospital": ["病院", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_13_1.mp3"],
    "hotel": ["ホテル", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_20_1.mp3"],
    "hungry": ["お腹が空いた", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_26_1.mp3"],
    "hurt": ["痛い", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_29_1.mp3"],
    "husband": ["夫", "https://storage.googleapis.com/eiken5/2024_12_24_14_24_32_1.mp3"],
    'idea': ['アイデア', 'https://storage.googleapis.com/eiken5/2024_12_24_14_24_36_1.mp3'],
    'important': ['大切', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_19_1.mp3'],
    'inside': ['中', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_23_1.mp3'],
    'interest': ['興味', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_27_1.mp3'],
    'interesting': ['面白い', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_29_1.mp3'],
    'internet': ['インターネット', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_34_1.mp3'],
    'invitation': ['招待', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_53_1.mp3'],
    'invite': ['招待する', 'https://storage.googleapis.com/eiken5/2024_12_24_16_03_57_1.mp3'],
    'joke': ['冗談', 'https://storage.googleapis.com/eiken5/2024_12_24_16_04_20_1.mp3'],
    'journey': ['旅', 'https://storage.googleapis.com/eiken5/2024_12_24_16_04_24_1.mp3'],
    'joy': ['喜び', 'https://storage.googleapis.com/eiken5/2024_12_24_16_04_27_1.mp3'],
    'kill': ['殺す', 'https://storage.googleapis.com/eiken5/2024_12_24_16_05_01_1.mp3'],
    'know': ['知る、知っている', 'https://storage.googleapis.com/eiken5/2024_12_24_16_05_26_1.mp3'],
    'learn': ['学ぶ', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_36_1.mp3'],
    'leave': ['出る', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_40_1.mp3'],
    'left': ['左', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_44_1.mp3'],
    'leg': ['脚', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_48_1.mp3'],
    'lemon': ['レモン', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_52_1.mp3'],
    'lesson': ['授業', 'https://storage.googleapis.com/eiken5/2025_01_07_01_15_57_1.mp3'],
    'letter': ['手紙', 'https://storage.googleapis.com/eiken5/2025_01_07_01_16_00_1.mp3'],
    'library': ['図書館', 'https://storage.googleapis.com/eiken5/2025_01_07_01_16_05_1.mp3'],
    'light': ['光', 'https://storage.googleapis.com/eiken5/2025_01_07_01_16_09_1.mp3'],
    'lion': ['ライオン', 'https://storage.googleapis.com/eiken5/2025_01_07_01_16_13_1.mp3'],
    'morning': ['朝', 'https://storage.googleapis.com/eiken5/2024_12_17_14_48_07_1.mp3'],
    'market': ['市場', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_13_1.mp3'],
    'many': ['多い', 'https://storage.googleapis.com/eiken5/2024_12_18_09_24_01_1.mp3'],
    'medicine': ['薬', 'https://storage.googleapis.com/eiken5/2024_12_17_14_49_32_1.mp3'],
    'marry': ['結婚する', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_18_1.mp3'],
    'meal': ['食事', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_25_1.mp3'],
    'mean': ['意味する、意地悪い', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_29_1.mp3'],
    'meet': ['会う', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_38_1.mp3'],
    'minute': ['分', 'https://storage.googleapis.com/eiken5/2025_01_07_01_17_46_1.mp3'],
    'no': ['いいえ', 'https://storage.googleapis.com/eiken5/2024_12_18_14_31_25_1.mp3'],
    'now': ['今', 'https://storage.googleapis.com/eiken5/2024_12_18_09_23_42_1.mp3'],
    'number': ['数字', 'https://storage.googleapis.com/eiken5/2025_01_07_01_27_37_1.mp3'],
    'only': ['ただ（ただそれだけかなど）', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_11_1.mp3'],
    'open': ['開ける', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_17_1.mp3'],
    'other': ['他の', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_26_1.mp3'],
    'orange': ['オレンジ', 'https://storage.googleapis.com/eiken5/2024_12_18_14_17_32_1.mp3'],
    'our': ['われわれの', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_30_1.mp3'],
    'out': ['外', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_40_1.mp3'],
    'outside': ['外（outと意味ほぼ一緒）', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_46_1.mp3'],
    'over': ['上に', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_49_1.mp3'],
    'own': ['自分の', 'https://storage.googleapis.com/eiken5/2025_01_07_01_28_53_1.mp3'],
    'person': ['かた', 'https://storage.googleapis.com/eiken5/2024_12_18_09_24_35_1.mp3'],
    'painful': ['痛い', 'https://storage.googleapis.com/eiken5/2024_12_18_09_23_33_1.mp3'],
    'path': ['道', 'https://storage.googleapis.com/eiken5/2025_01_07_01_29_48_1.mp3'],
    'pay': ['払う（お金で払うなど）', 'https://storage.googleapis.com/eiken5/2025_01_07_01_29_53_1.mp3'],
    'people': ['人々', 'https://storage.googleapis.com/eiken5/2025_01_07_01_30_04_1.mp3'],
    'perfect': ['完璧', 'https://storage.googleapis.com/eiken5/2025_01_07_01_30_09_1.mp3'],
    'phone': ['電話', 'https://storage.googleapis.com/eiken5/2025_01_07_01_30_13_1.mp3'],
    'picture': ['絵', 'https://storage.googleapis.com/eiken5/2025_01_07_01_37_50_1.mp3'],
    'piece': ['一片', 'https://storage.googleapis.com/eiken5/2025_01_07_01_37_54_1.mp3'],
    'pig': ['ぶた', 'https://storage.googleapis.com/eiken5/2025_01_07_01_37_57_1.mp3'],
    'pilot': ['パイロット', 'https://storage.googleapis.com/eiken5/2025_01_07_01_38_00_1.mp3'],
    'pink': ['ピンク', 'https://storage.googleapis.com/eiken5/2025_01_07_01_38_04_1.mp3'],
    'place': ['場所', 'https://storage.googleapis.com/eiken5/2025_01_07_01_38_08_1.mp3'],
    'plan': ['計画', 'https://storage.googleapis.com/eiken5/2025_01_07_01_38_12_1.mp3'],
    'plant': ['食物', 'https://storage.googleapis.com/eiken5/2025_01_07_01_38_16_1.mp3'],
    'queen': ['女王', 'https://storage.googleapis.com/eiken5/2025_01_07_01_39_57_1.mp3'],
    'question': ['質問', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_00_1.mp3'],
    'quick': ['素早い', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_04_1.mp3'],
    'quiet': ['静か', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_08_1.mp3'],
    'raise': ['上げる', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_24_1.mp3'],
    'reach': ['届く', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_30_1.mp3'],
    'reason': ['理由', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_46_1.mp3'],
    'restaurant': ['レストラン', 'https://storage.googleapis.com/eiken5/2025_01_07_01_58_07_1.mp3'],
    'remember': ['覚える', 'https://storage.googleapis.com/eiken5/2025_01_07_01_40_57_1.mp3'],
    'rule': ['規則', 'https://storage.googleapis.com/eiken5/2025_01_07_01_58_41_1.mp3'],
    'sleep': ['寝る', 'https://storage.googleapis.com/eiken5/2025_01_07_02_15_49_1.mp3'],
    'small': ['小さい', 'https://storage.googleapis.com/eiken5/2025_01_07_02_15_53_1.mp3'],
    'smell': ['匂い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_15_56_1.mp3'],
    'smile': ['笑う', 'https://storage.googleapis.com/eiken5/2025_01_07_02_15_58_1.mp3'],
    'snow': ['雪', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_02_1.mp3'],
    'sofa': ['ソファー', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_05_1.mp3'],
    'some': ['いくつか', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_08_1.mp3'],
    'someone': ['誰か', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_11_1.mp3'],
    'sometimes': ['時々', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_14_1.mp3'],
    'son': ['息子', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_17_1.mp3'],
    'song': ['歌', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_22_1.mp3'],
    'soon': ['もうすぐ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_25_1.mp3'],
    'sound': ['音', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_31_1.mp3'],
    'soup': ['スープ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_35_1.mp3'],
    'south': ['南', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_38_1.mp3'],
    'space': ['空間', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_41_1.mp3'],
    'speak': ['話す', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_44_1.mp3'],
    'special': ['特別', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_47_1.mp3'],
    'speed': ['速度', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_52_1.mp3'],
    'spell': ['つづる', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_55_1.mp3'],
    'spend': ['費やす', 'https://storage.googleapis.com/eiken5/2025_01_07_02_16_58_1.mp3'],
    'square': ['四角い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_06_1.mp3'],
    'stamp': ['切手', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_08_1.mp3'],
    'stand': ['立つ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_11_1.mp3'],
    'star': ['星', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_19_1.mp3'],
    'start': ['始める、始まる', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_25_1.mp3'],
    'stay': ['留まる、滞在する', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_33_1.mp3'],
    'steal': ['盗む', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_36_1.mp3'],
    'step': ['ステップ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_39_1.mp3'],
    'still': ['まだ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_42_1.mp3'],
    'stone': ['石', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_45_1.mp3'],
    'stop': ['止める、泊まる', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_49_1.mp3'],
    'story': ['物語', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_55_1.mp3'],
    'street': ['通り', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_58_1.mp3'],
    'strong': ['強い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_02_1.mp3'],
    'sunny': ['晴れ', 'https://storage.googleapis.com/eiken5/2024_12_18_14_16_57_1.mp3'],
    'spring': ['春', 'https://storage.googleapis.com/eiken5/2024_12_18_14_16_36_1.mp3'],
    'summer': ['夏', 'https://storage.googleapis.com/eiken5/2024_12_18_14_16_29_1.mp3'],
    'station': ['駅', 'https://storage.googleapis.com/eiken5/2024_12_18_14_03_05_1.mp3'],
    'store': ['店', 'https://storage.googleapis.com/eiken5/2024_12_18_14_03_00_1.mp3'],
    'student': ['学生', 'https://storage.googleapis.com/eiken5/2024_12_18_14_02_39_1.mp3'],
    'swim': ['泳ぐ', 'https://storage.googleapis.com/eiken5/2024_12_18_09_32_33_1.mp3'],
    'sad': ['悲しい', 'https://storage.googleapis.com/eiken5/2024_12_18_13_58_48_1.mp3'],
    'sleep': ['寝る', 'https://storage.googleapis.com/eiken5/2024_12_18_09_32_17_1.mp3'],
    'school': ['学校', 'https://storage.googleapis.com/eiken5/2024_12_18_09_30_20_1.mp3'],
    'side': ['側', 'https://storage.googleapis.com/eiken5/2024_12_18_09_24_19_1.mp3'],
    'shower': ['シャワーを浴びる', 'https://storage.googleapis.com/eiken5/2024_12_17_14_49_03_1.mp3'],
    'study': ['勉強する', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_08_1.mp3'],
    'stupid': ['馬鹿', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_12_1.mp3'],
    'subject': ['科目', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_15_1.mp3'],
    'subway': ['地下鉄', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_19_1.mp3'],
    'sugar': ['砂糖', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_22_1.mp3'],
    'sun': ['太陽', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_28_1.mp3'],
    'sunday': ['日曜日', 'https://storage.googleapis.com/eiken5/2025_01_07_02_18_32_1.mp3'],
    'supermarket': ['スーパー', 'https://storage.googleapis.com/eiken5/2025_01_07_02_30_27_1.mp3'],
    'sure': ['確かに、そうですね、いいよ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_30_36_1.mp3'],
    'surprise': ['びっくり', 'https://storage.googleapis.com/eiken5/2025_01_07_02_30_38_1.mp3'],
    'sorry': ['ごめんなさい', 'https://storage.googleapis.com/eiken5/2024_12_18_14_31_16_1.mp3'],
    'strawberry': ['いちご', 'https://storage.googleapis.com/eiken5/2024_12_18_14_17_28_1.mp3'],
    'snowy': ['雪', 'https://storage.googleapis.com/eiken5/2024_12_18_14_17_10_1.mp3'],
    'stormy': ['嵐', 'https://storage.googleapis.com/eiken5/2024_12_18_14_17_14_1.mp3'],
    'steal': ['盗む', 'https://storage.googleapis.com/eiken5/2025_01_07_02_17_36_1.mp3'],
    'teach': ['教える', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_03_1.mp3'],
    'team': ['チーム', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_08_1.mp3'],
    'terrible': ['酷い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_18_1.mp3'],
    'test': ['テスト', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_21_1.mp3'],
    'thank': ['感謝', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_24_1.mp3'],
    'them': ['彼ら', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_29_1.mp3'],
    'then': ['その時', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_33_1.mp3'],
    'there': ['そこ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_35_1.mp3'],
    'these': ['これらの', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_38_1.mp3'],
    'they': ['彼ら（themと文法的な使い方が違う）', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_41_1.mp3'],
    'thing': ['物', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_46_1.mp3'],
    'think': ['思う', 'https://storage.googleapis.com/eiken5/2025_01_07_02_31_56_1.mp3'],
    'thirsty': ['喉が渇く', 'https://storage.googleapis.com/eiken5/2025_01_07_02_32_05_1.mp3'],
    'thursday': ['木曜日', 'https://storage.googleapis.com/eiken5/2025_01_07_02_32_25_1.mp3'],
    'together': ['一緒', 'https://storage.googleapis.com/eiken5/2025_01_07_02_32_40_1.mp3'],
    'train': ['練習する', 'https://storage.googleapis.com/eiken5/2025_01_07_02_32_56_1.mp3'],
    'travel': ['旅行する', 'https://storage.googleapis.com/eiken5/2025_01_07_02_32_58_1.mp3'],
    'trip': ['旅行、旅', 'https://storage.googleapis.com/eiken5/2025_01_07_02_43_20_1.mp3'],
    'true': ['本当', 'https://storage.googleapis.com/eiken5/2025_01_07_02_43_29_1.mp3'],
    'try': ['試す', 'https://storage.googleapis.com/eiken5/2025_01_07_02_43_32_1.mp3'],
    'tuesday': ['火曜日', 'https://storage.googleapis.com/eiken5/2025_01_07_02_43_35_1.mp3'],
    'turn': ['曲がる、曲げる、番（私の番など）', 'https://storage.googleapis.com/eiken5/2025_01_07_02_43_37_1.mp3'],
    'what': ['何', 'https://storage.googleapis.com/eiken5/2025_01_07_02_45_52_1.mp3'],
    'when': ['いつ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_45_54_1.mp3'],
    'where': ['どこ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_45_58_1.mp3'],
    'which': ['どちら', 'https://storage.googleapis.com/eiken5/2025_01_07_02_46_00_1.mp3'],
    'white': ['白い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_46_03_1.mp3'],
    'who': ['誰', 'https://storage.googleapis.com/eiken5/2025_01_07_02_46_05_1.mp3'],
    'why': ['なぜ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_46_08_1.mp3'],
    'wide': ['広い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_06_1.mp3'],
    'wife': ['妻', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_10_1.mp3'],
    'wild': ['野生', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_13_1.mp3'],
    'window': ['窓', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_16_1.mp3'],
    'wish': ['願う、願い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_22_1.mp3'],
    'with': ['と一緒に', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_24_1.mp3'],
    'woman': ['女の人', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_27_1.mp3'],
    'word': ['言葉', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_30_1.mp3'],
    'work': ['仕事', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_33_1.mp3'],
    'world': ['世界', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_36_1.mp3'],
    'worry': ['心配する', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_40_1.mp3'],
    'write': ['書く', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_43_1.mp3'],
    'wrong': ['間違っている', 'https://storage.googleapis.com/eiken5/2025_01_07_02_57_47_1.mp3'],
    'yet': ['まだ', 'https://storage.googleapis.com/eiken5/2025_01_07_02_58_00_1.mp3'],
    'young': ['若い', 'https://storage.googleapis.com/eiken5/2025_01_07_02_58_05_1.mp3'],
    'you': ['あなた', 'https://storage.googleapis.com/eiken5/2024_12_17_14_48_35_1.mp3'],
}

raw_eiken4_grammar_vocab = {
    'must/have to/has to': ['〜しなければならない', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_18_1.mp3'],
    'may': ['〜かもしれない／〜してもよい', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_24_1.mp3'],
    'might': ['〜かもしれない　例：明日は雪が降るかもしれません。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_27_1.mp3'],
    'should': ['〜すべき　例：もっと野菜を食べるべきです。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_29_1.mp3'],
    'would like to': ['〜したい　例：夏に北海道へ行きたいです。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_33_1.mp3'],
    'be going to': ['〜するつもり　例：午後から買い物に行くつもりです。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_37_1.mp3'],
    'there is/are': ['〜がある　例：机の上にノートがあります。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_42_1.mp3'],
    'how many': ['いくつ', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_48_1.mp3'],
    'how much': ['どれくらい', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_52_1.mp3'],
    'how long': ['どのくらい長い', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_54_1.mp3'],
    'how far': ['どのくらい遠い', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_52_57_1.mp3'],
    'how often': ['どのくらいの頻度で　例：どのくらいの頻度で映画を見ますか？', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_00_1.mp3'],
    'too': ['〜すぎる　例：このかばんは重すぎます。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_05_1.mp3'],
    'enough': ['十分に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_08_1.mp3'],
    'before': ['〜の前に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_16_1.mp3'],
    'after': ['〜の後で', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_23_1.mp3'],
    'until': ['〜まで', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_27_1.mp3'],
    'while': ['〜している間に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_30_1.mp3'],
    'as': ['〜として／〜のように／例：彼は先生として働いています。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_34_1.mp3'],
    'if': ['もし', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_38_1.mp3'],
    'when': ['〜するとき　例：電話が鳴ったとき、料理をしていました。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_42_1.mp3'],
    'than': ['〜よりも　例：兄は私より背が高いです。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_48_1.mp3'],
    'as___as': ['〜と同じくらい...　例：このケーキはお母さんのケーキと同じくらいおいしいです。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_53_54_1.mp3'],
    'because of': ['〜のために　例：雪のために学校が休みになりました。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_54_01_1.mp3'],
    'in front of': ['〜の前に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_54_06_1.mp3'],
    'next to': ['〜の隣に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_54_11_1.mp3'],
    'between': ['〜の間に', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_54_16_1.mp3'],
    'both': ['両方。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_54_20_1.mp3'],
    'either A or B': ['AかBのどちらか', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_55_32_1.mp3'],
    'neither A nor B': ['AでもBでもない', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_55_50_1.mp3'],
    'each': ['それぞれの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_55_58_1.mp3'],
    'another': ['もう一つの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_03_1.mp3'],
    'other': ['他の', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_07_1.mp3'],
    'others': ['他の人々', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_11_1.mp3'],
    'the other': ['残りの一つ', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_20_1.mp3'],
    'most': ['ほとんどの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_30_1.mp3'],
    'all': ['すべての', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_34_1.mp3'],
    'some': ['いくつかの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_37_1.mp3'],
    'any': ['どれでも／いくつでも　例：どの本でも読んでいいですよ。', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_40_1.mp3'],
    'every': ['すべての', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_43_1.mp3'],
    'more': ['もっと多くの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_46_1.mp3'],
    'less': ['より少ない　（数えられないもの）', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_51_1.mp3'],
    'fewer': ['より少ない　（数えられるもの）', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_55_1.mp3'],
    'whose': ['だれの', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_56_59_1.mp3'],
    'kind of': ['種類', 'https://storage.googleapis.com/eiken4_grammar/2025_05_21_12_57_03_1.mp3'],
}


def add_furigana(text):
    result = kks.convert(text)
    return ''.join([f"<ruby>{item['orig']}<rt>{item['hira']}</rt></ruby>" if '\u4e00' <= item['orig'] <= '\u9fff' else item['orig'] for item in result])

eiken4_vocab = {
    key: [add_furigana(value[0]), value[1]] for key, value in raw_eiken4_vocab.items()
}
eiken4_grammar_vocab = {
    key: [add_furigana(value[0]), value[1]] for key, value in raw_eiken4_grammar_vocab.items()
}

eiken4_vocab1 = dict(list(eiken4_vocab.items())[:25])
eiken4_vocab2 = dict(list(eiken4_vocab.items())[25:50])
eiken4_vocab3 = dict(list(eiken4_vocab.items())[50:75])
eiken4_vocab4 = dict(list(eiken4_vocab.items())[75:100])
eiken4_vocab5 = dict(list(eiken4_vocab.items())[100:125])
eiken4_vocab6 = dict(list(eiken4_vocab.items())[125:150])
eiken4_vocab7 = dict(list(eiken4_vocab.items())[150:175])
eiken4_vocab8 = dict(list(eiken4_vocab.items())[175:200])
eiken4_vocab9 = dict(list(eiken4_vocab.items())[200:225])
eiken4_vocab10 = dict(list(eiken4_vocab.items())[225:250])
eiken4_vocab11 = dict(list(eiken4_vocab.items())[250:275])
eiken4_vocab12 = dict(list(eiken4_vocab.items())[275:299])




eiken4_vocab_practice = {
    "Kaito went to a movie (         ) today. He saw a movie called The Legend of Ivar.": ["picnic", "car", "start", "theater"],
    "Jason went to an amusement (         ) yesterday. He rode a big roller coaster.": ["knife", "star", "guy", "park"],
    "Jack went to a convenience (         ) in the afternoon to buy some tissues.": ["more", "park", "mart", "store"],
    "Hisako went to a shopping (         ) to buy some birthday presents for Mike.": ["person", "question", "start", "mall"],
    "Daniel went to an anime (         ) and did some cosplay.": ["panic", "toy", "manga", "event"],
    "Saki went to a coffee (         ) this morning. She drank a latte.": ["lake", "window", "family", "shop"],
    "Leo went to a book (         ) after school. He bought a comic book.": ["floor", "jump", "cool", "store"],
    "Ken went to a music (         ) last night. He saw his favorite band.": ["car", "video", "cloud", "concert"],
    "Amy went to a pet (         ) to buy food for her cat.": ["stop", "event", "rabbit", "shop"],
    "Mia went to a sushi (         ) for dinner with her family.": ["tree", "apple", "drama", "restaurant"],
    "Sho went to a sports (         ) to play basketball with friends.": ["cake", "train", "coffee", "center"],
    "Tom went to the city (         ) to see the mayor.": ["juice", "story", "hope", "hall"],
    "Hana went to a flower (         ) to buy roses for her mom.": ["horse", "mountain", "star", "shop"],
    "Ryan went to an art (         ) to see paintings by Picasso.": ["fish", "dream", "pencil", "museum"],
    "Jessie lives in a small apartment, but she wants to move to a big (         ) in the future.": ["tornado", "star", "spice", "house"],
    "Jon goes to a big high school with many students, but he wants to go to a small (         ) after graduating.": ["quiz", "stranded", "elementary school", "university"],
    "Emily works at a family-owned business, but she wants to work at a big (         ) when she's older.": ["darkness", "competition", "pool", "company"],
    "Kirito lives in a small (         ), but after studying English, he would like to live in New York.": ["part", "game", "curtain", "town"],
    "Haruka works at a regular clothes shop, but in the future, she wants to become a fashion (         ).": ["steal", "bike", "game", "designer"],
    "Tomo studies English every day because he wants to work in another (         ) someday.": ["banana", "machine", "castle", "country"],
    "Mika lives in a quiet (         ) near the mountains, but she wants to live in the city.": ["light", "jump", "school", "village"],
    "Ken plays video games at home, but one day he wants to make his own (         ).": ["magic", "dancer", "window", "game"],
    "Anna practices singing a lot because she wants to be a famous (         ) someday.": ["street", "idea", "pencil", "singer"],
    "Leo watches cooking shows every day because he wants to be a good (         ).": ["hand", "break", "number", "chef"],
    "Kaito is good at math and wants to be a (         ) when he grows up.": ["river", "friend", "monster", "scientist"],
    "Naoki likes animals and hopes to become a (         ) in the future.": ["coffee", "rocket", "artist", "vet"],
    "Ayaka is good at drawing and wants to be a manga (         ) one day.": ["country", "stairs", "map", "artist"],
    "Yuki studies hard at school because he wants to be a (         ) when he grows up.": ["plant", "jacket", "beach", "doctor"],
    "Peter is a carpenter in Japan. His (         ) is a firefighter in Sweden.": ["dog", "apple", "dart", "son"],
    "Mark is 40 years old. His (         ) is 90 years old.": ["cat", "son", "daughter", "grandmother"],
    "Tyler is a chef. His (         ) takes care of the home while he's working.": ["wrong", "passion", "juice", "wife"],
    "Haruka is a marathon runner. Her (         ) is a soccer player.": ["parking", "pet", "mask", "brother"],
    "Kevin likes chocolate. Everyone in his (         ) loves chocolate too.": ["math", "random", "motor", "family"],
    "Hana is nine years old. Her (         ) is only two.": ["pencil", "job", "moon", "sister"],
    "Takumi is a student. His (         ) is a doctor at the hospital.": ["car", "juice", "paint", "mother"],
    "Julia is from Canada. Her (         ) lives in Tokyo.": ["sandwich", "keyboard", "clock", "father"],
    "Ken's (         ) works at a flower shop. She loves flowers.": ["glove", "truck", "mountain", "aunt"],
    "Yumi is an elementary school (         ). Her students like her very much.": ["calculator", "minute", "song", "teacher"],
    "Mayu didn't have a bus (         ), so she went to the reception to buy one.": ["train", "pan", "shoe", "ticket"],
    "Darin didn't have any running (         ), so he went to buy a pair before the school marathon.": ["post", "often", "spring", "shoes"],
    "David forgot his text (         ), so he borrowed one from the teacher.": ["whatever", "black", "swag", "book"],
    "Jake often forgot to brush his (         ), so now he only has 5 left.": ["spoons", "tomatoes", "books", "teeth"],
    "Zoro doesn't watch the (         ), so he didn't know about the big earthquake.": ["fantasies", "weather", "stars", "news"],
    "Keiko couldn't find her house (         ), so she waited outside.": ["cake", "soda", "planet", "key"],
    "Oscar didn’t hear his (         ) and woke up late for school.": ["grape", "animal", "banana", "alarm"],
    "Taku forgot to take his (         ) to school, so he couldn’t write.": ["glasses", "hat", "toy", "pencil"],
    "Mina couldn't see the board. I think she needs new (         ).": ["teeth", "socks", "gloves", "glasses"],
    "Erika got a (         ) from her grandmother on her birthday.": ["river", "bowl", "leaf", "present"],
    "Kai always brings his (         ) to school to carry his books.": ["sandwich", "pillow", "guitar", "bag"],
    "Riko keeps her lunch in a small (         ).": ["mirror", "napkin", "cloud", "box"],
    "Jake wants to (         ) around Japan. He wants to visit many shrines and temples.": ["strike", "call", "remove", "travel"],
    "Denis wants to go (         ) at the lake. He hopes to catch some for dinner tonight.": ["collecting", "running", "fighting", "fishing"],
    "Helena wants to become a (         ) at a famous university.": ["limit", "marathon", "question", "professor"],
    "Mako wants to (         ) songs at big concerts. She hopes to become a famous idol.": ["partner", "like", "fish", "sing"],
    "Mihiro wants to (         ) and celebrate Christmas together with her family.": ["risk", "there", "this is", "stay home"],
    "Naruto wants to learn more (         ). He hopes that he can make many American friends in the future.": ["American", "America", "England", "English"],
    "Ava wants to (         ) a dog when she grows up. She loves animals.": ["juice", "fly", "paint", "have"],
    "Liam wants to (         ) a doctor because he likes helping people.": ["read", "draw", "open", "become"],
    "Mia wants to (         ) in the sea. She is taking swimming lessons.": ["jump", "climb", "play", "swim"],
    "Noah wants to be able to (         ) faster, so he practices every morning.": ["write", "eat", "look", "run"],
    "Sakura wants to (         ) to America next year to study.": ["bake", "carry", "paint", "go"],
    "Leo wants to (         ) the piano better. He practices every day.": ["close", "grow", "show", "play"],
    "Yui wants to (         ) her room before the guests come.": ["break", "hide", "throw", "clean"],
    "Taro wants to (         ) many books this year.": ["see", "cook", "yell", "read"],
    "Isla wants to (         ) a letter to her friend in Canada.": ["drink", "fix", "run", "write"],
    "David loves (         ). He is a member of the music club.": ["scratching", "weight lifting", "running", "singing"],
    "Ena loves kendo. She is a (         ) of the kendo team.": ["good", "monkey", "try", "member"],
    "Patrick is a (         ) at the famous Ivar University.": ["pitcher", "tower", "man", "student"],
    "Henry is a (         ) in the U.S.A. He hopes to become president one day.": ["figure skater", "dancer", "singer", "politician"],
    "Kim is a famous (         ) in Korea. He is very handsome. He can sing and dance well too.": ["point", "book", "number", "idol"],
    "Yuto is a (         ) on the soccer team. He plays every Saturday.": ["pencil", "clap", "forest", "player"],
    "Sarah is a great (         ). She always draws beautiful pictures in class.": ["bottle", "lemon", "joke", "artist"],
    "Leon is a new (         ) in Tokyo. He teaches English to junior high students.": ["oven", "candy", "rock", "teacher"],
    "Naomi is a (         ) at a pet shop. She loves animals.": ["dance", "water", "bag", "clerk"],
    "Tom is a (         ) at the city hospital. He helps many patients.": ["banana", "jungle", "pocket", "doctor"],
    "Ayaka is a high school (         ). She studies math and science every day.": ["chair", "house", "sky", "student"],
    "Jack is a (         ) at a famous restaurant. He makes pasta and pizza.": ["paper", "puzzle", "queen", "chef"],
    "Hana is a popular (         ) on TV. She tells people the news every night.": ["glove", "snow", "notebook", "announcer"],
    "Isaac is a strong (         ). He can carry very heavy things.": ["answer", "melon", "train", "weightlifter"],
    "Tom used a (         ) to cut the fruit.": ["fan", "slipper", "chair", "knife"],
    "Nancy used a (         ) to learn English called Ibaru Eigo.": ["line", "string", "monitor", "website"],
    "Mary used a (         ) to clean the room.": ["oven", "bomb", "hammer", "vacuum cleaner"],
    "Danny used an (         ) to cook the food.": ["marker", "kite", "phone", "oven"],
    "Lina used a (         ) to measure the length of her pencil.": ["story", "timer", "scale", "ruler"],
    "Ben used a (         ) to write a letter to his friend.": ["spoon", "lamp", "cube", "pen"],
    "Lily used a (         ) to carry her books to school.": ["hat", "carpet", "plate", "backpack"],
    "Sally used a (         ) to take pictures at the party.": ["box", "clock", "bottle", "camera"],
    "John used a pair of (         ) to cut paper for his art project.": ["ball", "glove", "shoe", "scissors"],
    "Emma used (         ) to listen to music on the bus.": ["tables", "chairs", "books", "headphones"],
    "Jack used a (         ) to clean his shoes before school.": ["ball", "lamp", "clock", "brush"],
    "Mia used a (         ) to carry water from the well.": ["bag", "phone", "fan", "bucket"],
    "Marci got cold playing in the snow, so she (         ) a jacket.": ["walked on", "stood by", "took off", "put on"],
    "Tim got sweaty playing soccer, so he (         ) his T-shirt.": ["faced", "punished", "destroyed", "changed"],
    "Jay got tired studying English, so he took a (         ).": ["when", "right", "win", "break"],
    "Luna got hungry watching a cooking show on the TV, so she (         ) a sandwich.": ["broke", "smashed", "stopped", "made"],
    "Leila got bored waiting for the train, so she (         ) games on her phone.": ["where", "must", "did", "played"],
    "Anna got thirsty after running, so she (         ) some water.": ["jumped", "held", "broke", "drank"],  
    "Mark got cold waiting outside, so he (         ) his coat.": ["opened", "threw", "lost", "put on"],  
    "Sara got sleepy during the movie, so she (         ) her eyes.": ["opened", "banned", "washed", "closed"],  
    "John got wet in the rain, so he (         ) an umbrella.": ["broke", "threw", "lost", "used"],  
    "Emily got scared by the thunder, so she (         ) under the blanket.": ["ran", "stood", "jumped", "hid"],  
    "Tom got excited when he won the game, so he (         ) loudly.": ["cried", "slept", "jumped", "cheered"],  
    "Lily got dirty while gardening, so she (         ) her hands.": ["marked", "played", "danced", "washed"],  
    "Mia got tired after school, so she (         ) down on the sofa.": ["jumped", "stood", "ran", "sat"],  
    "The test was not so (         ). Most students got a perfect score.": ["damaged", "cool", "easy", "difficult"],
    "The party was very (         ). Most people stayed until 6 a.m.": ["sometimes", "risky", "gas", "fun"],
    "Our teacher was very (         ). He screamed at Jack and Emi and sent Kouta back home.": ["cloudy", "funny", "easy", "angry"],
    "The game was very (         ). We played it for 10 hours yesterday.": ["surprising", "mad", "bad", "exciting"],
    "The computer was (         ). So we used our phones instead.": ["mix", "soft", "cool", "broken"],
    "The movie was really (         ). Everyone laughed a lot.": ["quiet", "long", "dark", "funny"],  
    "The weather was (         ) yesterday. We stayed inside all day.": ["boy", "strong", "calm", "stormy"],  
    "The food at the restaurant was (         ). I want to eat there again.": ["cold", "random", "small", "delicious"],  
    "The road was very (         ) after the heavy rain. Cars moved slowly.": ["smooth", "wide", "clean", "slippery"],  
    "The book was so (         ) that I finished it in one day.": ["heavy", "loud", "quiet", "interesting"],  
    "The teacher was very (         ) when the students were noisy.": ["happy", "tall", "cool", "angry"],    
    "The music at the concert was very (         ). Everyone was dancing.": ["slow", "quiet", "juicy", "exciting"],  
    "The city is very (         ) at night. There are many lights everywhere.": ["dark", "empty", "cold", "bright"],  
    "When it's rainy, Mio likes to stay (         ) and read books.": ["dart", "band", "by", "home"],
    "When it's sunny, Sora likes to go to the swimming (         ) with his friends.": ["sun", "first", "base", "pool"],
    "When it's hot, Cathy always turns on both the fan and the air (         ).": ["dryer", "reader", "blower", "conditioner"],
    "When it's windy, Ken likes to fly a (         ) in the park.": ["ball", "pipe", "net", "kite"],
    "When it's cold, Aki wears a (         ) to keep warm outside.": ["hat", "sock", "shoe", "jacket"],
    "When it's snowy, Yuki enjoys making a (         ) with her family.": ["cake", "sandwich", "toy", "snowman"],
    "When it's cloudy, Taro likes to take a (         ) around the neighborhood.": ["smart", "station", "train", "walk"],
    "When it's foggy, drivers should use their (         ) lights.": ["yellow", "red", "green", "fog"],
    "When it's stormy, Emi stays (         ) and watches movies at home.": ["outside", "school", "park", "inside"],
}

eiken4_conversation_vocab_practice = {
    "A: Did you (         ) the cooking contest? B: Yes, I did. This is the happiest day of my life.": ["sprint", "spell", "forget", "win"],
    "A: Did you (         ) to school today, Randy? B: Yes, I did. It was super boring.": ["ground", "power", "break", "go"],
    "A: Did you (         ) breakfast today, Jimmy? B: No, I didn't. I'm so hungry.": ["fixed", "much", "cast", "have"],
    "A: Did you (         ) the laundry today? B: Sorry, I forgot to do it. So we have no clean clothes for tomorrow.": ["print", "direct", "forgive", "do"],
    "A: Did you (         ) the car to work today? B: Yes, I did.": ["anger", "trace", "punish", "drive"],
    "A: Did you (         ) your homework last night? B: Yes, I did. It was really hard.": ["miss", "jump", "fail", "finish"],
    "A: Did you (         ) your friend a birthday present? B: Yes, I did. She loved it.": ["sing", "bake", "count", "give"],
    "A: Did you (         ) the test today? B: Yes, I think I did well.": ["float", "shout", "clap", "take"],
    "A: Did you (         ) the movie last night? B: No, I was too tired.": ["fix", "listen", "build", "watch"],
    "A: Did you (         ) your hands before dinner? B: Yes, Mom.": ["close", "paint", "carry", "wash"],
    "A: Did you (         ) the lights before leaving the room? B: Oops! I forgot.": ["climb", "draw", "plant", "turn off"],
    "A: Did you (         ) the guitar at the party? B: Yes! Everyone clapped.": ["cook", "ride", "wear", "play"],
    "A: Did you (         ) your jacket at school? B: Oh no! I think I did.": ["hide", "move", "drop", "lose"],
    "A: Did you (         ) your name on the paper? B: Yes, it's at the top.": ["taste", "push", "open", "write"],
    "A: Did you (         ) the door when you came in? B: Yes, I did.": ["sing", "drive", "brush", "close"],
    "A: What's wrong, Mei? B: I'm (         ). I want to eat pizza.": ["bananas", "cool", "happy", "hungry"],
    "A: What's wrong, Karin? B: I'm (         ). I just lost at my favorite game.": ["smart", "happy", "this", "sad"],
    "A: What's wrong, Bob? B: I'm (         ). I need a fan or air conditioner": ["boy", "interesting", "slow", "hot"],
    "A: What's wrong, Danny? B: I'm (         ). Do you have anything to drink here?": ["hungry", "brain", "masterful", "thirsty"],
    "A: What's wrong, Martin? B: I'm (         ). There's a big spider on my bed.": ["excited", "thirsty", "hungry", "scared"],
    "A: What's wrong, Ken? B: I'm (         ). I want to go to sleep.": ["blue", "kind", "ready", "tired"],
    "A: What's wrong, Yuki? B: I'm (         ). I have a test tomorrow.": ["fun", "early", "fast", "nervous"],
    "A: What's wrong, Emma? B: I'm (         ). I have nothing to do.": ["old", "wet", "open", "bored"],
    "A: What's wrong, Mark? B: I'm (         ). My dog is at the hospital.": ["round", "green", "cool", "sad"],
    "A: What's wrong, Amy? B: I'm (         ). I ate too much lunch.": ["dry", "sweet", "near", "full"],
    "A: What's wrong, Miki? B: I'm (         ). I lost my umbrella.": ["clean", "red", "easy", "upset"],
    "A: What's wrong, Sara? B: I'm (         ). I forgot my homework.": ["sharp", "early", "young", "embarrassed"],
    "A: Why is Maria so (         ) with you? B: Because I bought her a nice present for her birthday.": ["angry", "foot", "man", "happy"],
    "A: Why is Ken not (         ) with you? B: I don't know. Maybe he's angry.": ["must", "style", "ice cream", "talking"],
    "A: Why is Jon (         )? B: He didn't pass the exam.": ["running", "marking", "celebrating", "crying"],
    "A: Why is Zoro not (         ) you? B: I don't know. I think he got lost somewhere on the way home.": ["stone", "happen", "part", "with"],
    "A: Why is Maria so (         ) today? B: She missed the bus in the morning and got yelled at by our teacher.": ["problem", "donkey", "big", "angry"],
    "A: Why is Anna (         ) today? B: She got a new puppy.": ["boring", "sock", "forget", "happy"],
    "A: Why is Yuta (         )? B: He fell off his bike.": ["painting", "writing", "watching", "crying"],
    "A: Why is Taro not (         ) to you? B: I think he's still mad about yesterday.": ["cloud", "shoe", "color", "talking"],
    "A: Why is John (         ) to school today? B: He has a stomachache.": ["early", "playing", "long", "not going"],
    "A: Why is Lisa (         )? B: She got 100 points on her English test!": ["window", "fish", "dark", "smiling"],
    "A: Why is Mika (         )? B: Her cat is sick.": ["cool", "table", "cold", "sad"],
    "A: Why is Tom (         )? B: He forgot to bring his homework again.": ["small", "banana", "cake", "embarrassed"],
    "A: Why is Ken (         ) today? B: His favorite team lost the game.": ["strong", "hat", "write", "upset"],
    "A: Did your sister help you with your homework? B: Yes. She's very (         ).": ["last", "might", "radio", "helpful"],
    "A: Did Michael help us with the project? B: Only a little bit. He's (         ).": ["right", "winner", "good", "lazy"],
    "A: Did our teacher give us any homework? B: Yes. He gave us a lot of homework. He's very (         ) with us.": ["water", "mind", "lazy", "strict"],
    "A: Did Carl help you fix your car? B: No. He's not very (         ) to me.": ["mart", "snap", "bat", "nice"],
    "A: Did Noa tell the teacher about the accident? B: No. He's (         ) of our teacher.": ["asked", "smiled", "marked", "scared"],
    "A: Did your brother wash the dishes? B: Yes. He's very (         ).": ["cookie", "fast", "many", "helpful"],
    "A: Did Julie clean her room? B: No, she's very (         ).": ["short", "lamp", "fish", "lazy"],
    "A: Did your dad cook dinner? B: Yes. He's a really (         ) cook.": ["tall", "fun", "cake", "good"],
    "A: Did the boy tell the truth? B: Yes. He's very (         ).": ["walk", "bright", "funny", "honest"],
    "A: Did your sister go outside alone? B: No. She's (         ) of the dark.": ["book", "milk", "clap", "afraid"],
    "A: Did that student forget his homework? B: Yes. He's really (         ).": ["fast", "quiet", "smile", "careless"],
    "A: Are you (         ) for the marathon tomorrow, Kaito? B: Yes, I am. I practiced running 10 kilometers everyday for 1 year.": ["ring", "mystery", "cool", "ready"],
    "A: Are you (         ) of the school lunch? B: Yes, I am. It's always the same food every day.": ["parking", "woman", "happy", "tired"],
    "A: Are you (         ) for the amusement park tomorrow? B: Yes, I am. I want to try the biggest roller coaster they have.": ["mixed", "muddy", "cold", "excited"],
    "A: Are you (         ) to the birthday party tomorrow, Riki? B: Yes, I am. I have a really nice present ready.": ["pencil", "boy", "moving", "going"],
    "A: Are you (         ) to Tokyo, Hisako? B: Yes, I am. I got a new job there.": ["walking", "fighting", "staying", "moving"],
    "A: Are you (         ) for the English test tomorrow? B: Yes, I studied all week.": ["nice", "box", "sleepy", "ready"],
    "A: Are you (         ) about your speech? B: Yes, I have never spoken in front of many people before.": ["strong", "fun", "yellow", "nervous"],
    "A: Are you (         ) for summer vacation? B: Yes, I can't wait to go to the beach.": ["open", "quiet", "dark", "excited"],
    "A: Are you (         ) about moving to a new city? B: Yes, I will miss my friends.": ["tall", "quick", "round", "sad"],
    "A: Are you (         ) to see grandma this weekend? B: Yes, I haven't seen her in months.": ["hard", "wrong", "quiet", "happy"],
    "A: Are you (         ) about your test results? B: Yes, I think I did really well.": ["blue", "head", "book", "confident"],
    "A: Are you (         ) to help me tomorrow? B: Yes, I don't have any plans.": ["map", "grape", "short", "free"],
    "A: Are you (         ) of going to the haunted house? B: A little.": ["sunny", "fun", "giant", "scared"],
    "A: Can I use your phone now? B: (         ) a minute. I need to finish this game first.": ["wake", "snake", "bait", "wait"],
    "A: Can I go to the bathroom? B: (         ) wait until the lesson is finished.": ["where", "they", "go", "please"],
    "A: Can I talk on my phone here? B: NO, you can't. This is a (         ).": ["dark", "phone", "rice field", "library"],
    "A: Can I talk with my mother? B: (         ), when she finishes work.": ["Lonely", "Brick", "Bank", "Later"],
    "A: Can I apply for jobs here? B: Yes, you can. But you need to show us your (         ) first.": ["point", "job", "spirit", "ID"],
    "A: Can I borrow your pencil? B: (         ). Just give it back later.": ["Door", "Sleep", "Chair", "Sure"],
    "A: Can I eat this cake? B: Not yet. It's for the (         ).": ["mouse", "clock", "place", "party"],
    "A: Can I open the window? B: (         ). It's very hot in here.": ["Far", "Moon", "Often", "Yes"],
    "A: Can I come to your house today? B: Sorry, I'm (         ) now.": ["glue", "fun", "pie", "busy"],
    "A: Can I take this seat? B: No, it's (         ).": ["up", "free", "face", "taken"],
    "A: Can I play video games now? B: Not yet. You need to finish your (         ) first.": ["drive", "sock", "apple", "homework"],
    "A: Can I buy this toy? B: Yes, but do you have enough (         )?": ["sun", "hair", "milk", "money"],
    "A: Can I eat lunch now? B: Yes, it's almost (         ).": ["pen", "brush", "early", "noon"],
    "A: It's very cold today, Mia. You should (         ) a jacket. B: Ok, mom. I will.": ["sink", "joke", "dry", "wear"],
    "A: It's rainy today, Haruto. You should (         ) your umbrella. B: Ok, dad. I will.": ["wake", "make", "shake", "take"],
    "A: It's snowing outside, Bart! We should (         ) a snowman. B: Ok, Kenny. Let's go!": ["crash", "mask", "drink", "make"],
    "A: It's late, Ivar. You should stop playing games and go to (         ). B: No. I want to play more.": ["octopus", "ready", "my", "bed"],
    "A: It's dark outside, Naruto. Take a (         ) with you. B: Ok. Hmmm, maybe I will stay home.": ["front", "work", "sneaker", "flashlight"],
    "A: It's raining today. You (         ) take your umbrella. B: Right, thanks!": ["draw", "buy", "read", "should"],
    "A: You (         ) be quiet in the library. B: OK, I'll whisper.": ["laugh", "run", "sleep", "must"],
    "A: You (         ) wear a seatbelt in the car. B: I always do.": ["sing", "forget", "play", "have to"],
    "A: You (         ) do your homework before dinner. B: Alright, I will.": ["skip", "read", "call", "must"],
    "A: You (         ) clean your room before you go out. B: Aw man... OK.": ["paint", "watch", "cry", "have to"],
    "A: We (         ) bring our textbooks to class. B: I already put mine in my bag.": ["jump", "close", "eat", "must"],
    "A: You look tired, Ken. You should (         ) a rest. B: Yeah, I think I will.": ["paint", "kick", "give", "take"],
    "A: It's very hot today. You should drink some (         ). B: Ok, I will.": ["rock", "light", "meat", "water"],
    "A: It's dangerous here, Nami. You should (         ) careful. B: OK, I'll watch my step.": ["eat", "throw", "smell", "be"],
    "A: I'm very sleepy. Can we take a 30 minute nap? B: Yes, let's (         ) a bit.": ["went", "buy", "money", "sleep"],
    "A: I'm really hungry. Can we eat something? B: Okay, let's have a (         ) then continue.": ["error", "wind", "water", "snack"],
    "A: I'm really tired. Can we take a break? B: Okay, let's lie (         ) on the grass a bit.": ["right", "left", "up", "down"],
    "A: My shoulders are very stiff. Can you give me a massage? B: Okay. Sit (         ) on the chair and I will massage your shoulders.": ["practice", "solve", "defend", "down"],
    "A: I'm very tired. Do we have to walk? B: No. We can (         ) the car if you want.": ["hike", "like", "fake", "take"],
    "A: It's hot today. Can we go swimming? B: Yes, let's (         ) to the pool.": ["run", "jump", "play", "go"],
    "A: I'm thirsty. Can I have some water? B: Sure, let's (         ) some from the kitchen.": ["cook", "rest", "eat", "get"],
    "A: I can't find my book. Can I borrow yours? B: Sure, you can (         ) it after class.": ["my", "throw", "break", "use"],
    "A: I'm hungry. Can we eat now? B: Yes, let's (         ) lunch together.": ["sleep", "play", "work", "have"],
    "A: I'm late for the meeting. Should I call? B: Yes, you should (         ) them now.": ["watch", "ignore", "wait", "call"],
    "A: How (         ) is the bus ride? B: It's about 2 hours.": ["start", "amazing", "big", "long"],
    "A: How (         ) are you, Ivar? B: I'm 130kg.": ["port", "fix", "rest", "heavy"],
    "A: How (         ) is this game? B: It's $40.": ["least", "few", "many", "much"],
    "A: How (         ) apples do you have? B: I have two. Do you want one?": ["fancy", "spring", "windy", "many"],
    "A: How (         ) is Mt. Fuji? B: It's 3776 meters.": ["tall", "low", "way", "high"],
    "A: How (         ) is the exam? B: It's 60 minutes long.": ["fast", "deep", "short", "long"],
    "A: How (         ) are your shoes? B: They are size 25.": ["bark", "thin", "heavy", "big"],
    "A: How (         ) water do you drink every day? B: About two liters.": ["mart", "little", "some", "much"],
    "A: How (         ) people are in your class? B: There are 30 students.": ["tall", "long", "few", "many"],
    "A: How (         ) does it take to get to school? B: About 30 minutes by bus.": ["slow", "short", "fast", "long"],
    "A: Are you doing the laundry, mom? I'll help you. B: Thanks, Jane. Please (         ) the clothes over there, in the machine.": ["hurt", "number", "van", "put"],
    "A: Are you cooking food, Jon? Do you need anything? B: Please buy some (         ).": ["computers", "stones", "wood", "onions"],
    "A: Are you building our new house, dad? I can help. B: Please bring me a (         ).": ["cloud", "dictionary", "tiger", "hammer"],
    "A: Are you doing your homework? I can help. B: Yes. Please help me with my (         ).": ["fan", "place", "drink", "math"],
    "A: Are you going to play tennis? Can I join? B: Okay. Bring your (         ).": ["watch", "young", "money", "racket"],
    "A: Are you planting flowers, dad? Do you need help? B: Yes, please bring some (         ).": ["stones", "papers", "cans", "soil"],
    "A: Are you fixing the bike, Ken? B: Yes. Please hand me the (         ).": ["ball", "cup", "hat", "wrench"],
}

eiken4_grammar_practice = {
    "Ivar is good (         ) cooking. He is in the cooking club.": ["is", "of", "on", "at"],
    "Jon is scared (         ) insects. He really hates spiders.": ["at", "under", "are", "of"],
    "Anna is interested (         ) science. She reads science books every day.": ["on", "to", "for", "in"],
    "We are late (         ) school. Let’s hurry!": ["is", "at", "on", "for"],
    "He is bad (         ) remembering names.": ["on", "to", "as", "at"],
    "They are afraid (         ) the dark.": ["on", "with", "for", "of"],
    "She is good (         ) drawing animals.": ["in", "with", "of", "at"],
    "Tom is proud (         ) his brother.": ["at", "in", "to", "of"],
    "We are tired (         ) walking so much.": ["for", "in", "on", "of"],
    "He is famous (         ) his music.": ["at", "with", "on", "for"],
    "I'm worried (         ) my test tomorrow.": ["at", "with", "to", "about"],
    "They are full (         ) energy.": ["at", "in", "for", "of"],
    "She is kind (         ) animals.": ["on", "then", "about", "to"],
    "My mother is busy (         ) cooking dinner.": ["at", "for", "in", "with"],
    "James was (         ) cookies after dinner. I think he should be careful with his diet.": ["ate", "eat", "eats", "eating"],
    "Kaito (         ) video games for 10 hours yesterday. He play less and study more.": ["plays", "play", "playing", "played"],
    "I (         ) a movie with my family last night.": ["watch", "watches", "watching", "watched"],
    "My sister is (         ) a letter to her friend now.": ["wrote", "writes", "write", "writing"],
    "They (         ) to the park every Sunday when they were kids.": ["go", "goes", "going", "went"],
    "Tom (         ) lunch when I called him.": ["has", "have", "had", "was having"],
    "We (         ) English when the teacher came in.": ["study", "studies", "studied", "were studying"],
    "She (         ) her homework before dinner yesterday.": ["do", "does", "doing", "did"],
    "I (         ) to music while walking to school this morning.": ["listen", "listens", "listened", "was listening"],
    "The boys (         ) soccer when it started to rain.": ["plays", "playing", "play", "were playing"],
    "Every Friday, Kento stays up (         ) than his parents because he loves watching long movies.": ["latest", "as late", "late", "later"],
    "This morning, I woke up the (         ) in my family. So I made everyone breakfast before they woke up.": ["very early", "early", "earlier", "earliest"],
    "That test was the (         ) one we've had this year. Everyone was confused.": ["most hard", "hard", "harder", "hardest"],
    "This math problem is (         ) than the one we did yesterday.": ["easy", "more easy", "easiest", "easier"],
    "That was the (         ) movie I've ever seen. I couldn't stop laughing.": ["fun", "more fun", "funnier", "funniest"],
    "Among all the runners, Ken was the (         ). He finished first!": ["fast", "faster", "more fast", "fastest"],
    "I think English is (         ) than science.": ["the most fun", "fun", "funnest", "more fun"],
    "Mount Fuji is the (         ) mountain in Japan.": ["more tall", "taller", "tall", "tallest"],
    "This cake is (         ) than the one we had yesterday.": ["good", "more good", "gooder", "better"],
    "Of all the cats, Tama is the (         ). He always sleeps on my lap.": ["friendly", "more friendly", "friendlier", "friendliest"],
    "My brother is (         ) than me, but I'm stronger.": ["tall", "more tall", "tallest", "taller"],
    "It was Sarah`s birthday yesterday. So I (         ) a cake for her.": ["is baking", "bakes", "baking", "baked"],
    "The weather is very nice today. So we will (         ) to the beach.": ["going", "went", "gone", "go"],
    "Ken didn't bring an umbrella, so he (         ) wet in the rain.": ["is getting", "get", "gotten", "got"],
    "It's my dad's birthday next week. I will (         ) him a present.": ["gave", "gives", "giving", "give"],
    "We were hungry, so we (         ) some sandwiches.": ["makes", "make", "making", "made"],
    "Tomorrow is a holiday, so we will (         ) home all day.": ["staying", "stayed", "stays", "stay"],
    "I (         ) my homework last night before watching TV.": ["doing", "does", "do", "did"],
    "Look at those clouds! It will probably (         ) soon.": ["rained", "raining", "rains", "rain"],
    "My mom (         ) me to the zoo last weekend.": ["taking", "takes", "take", "took"],
    "He is tired, so he will (         ) a nap after lunch.": ["took", "taking", "takes", "take"],
    "There are 2 new types of hamburgers at my favorite restaurant. The big one is (         ) expensive than the small one.": ["many", "most", "much", "more"],
    "There are 10 boys on the soccer team, but there are (         ) more on the basketball team. They have 50 boys.": ["much", "most", "more", "many"],
    "Tom has (         ) friends in class than Ken. Ken only has one or two.": ["much", "many", "most", "more"],
    "I saw (         ) interesting animals at the zoo yesterday.": ["much", "mosts", "most", "many"],
    "I think science is (         ) more difficult than English.": ["much", "many", "most", "more"],
    "There are (         ) people in the park today than yesterday.": ["many", "much", "most", "more"],
    "How (         ) water do you drink every day?": ["mores", "more", "most", "much"],
    "A: Did you get any help from the teacher yesterday? B:Yes. He (         ) me with my math homework.": ["helper", "helping", "help", "helped"],
    "A: Did you have fun at the party last week? B:Yes. I (         ) a lot of fun.": ["haven't", "has", "have", "had"],
    "A: Did you watch the new movie last weekend? B: Yes. I (         ) it yesterday.": ["watches", "watching", "watch", "watched"],
    "A: Did your friend come to the party? B: Yes. He (         ) here at 7 p.m.": ["come", "coming", "comes", "came"],
    "A: Did you finish your homework? B: Yes. I (         ) it before dinner.": ["finish", "finishing", "finishes", "finished"],
    "A: Did Tom help you with the project? B: Yes. He (         ) me a lot.": ["helper", "helping", "help", "helped"],
    "A: Did you go to the zoo last Saturday? B: Yes. I (         ) many animals there.": ["see", "sees", "seeing", "saw"],
    "A: Did your parents visit the museum? B: Yes. They (         ) it very interesting.": ["find", "finding", "finds", "found"],
    "A: Did Sarah play tennis yesterday? B: Yes. She (         ) for two hours.": ["play", "playing", "plays", "played"],
    "A: Did you like the new restaurant? B: Yes. I (         ) their food was delicious.": ["thinked", "thinking", "thinks", "thought"],
    "A: Did Ken call you last night? B: Yes. He (         ) me at 9 o’clock.": ["call", "calling", "calls", "called"],
    "A: Did you enjoy the concert? B: Yes. I (         ) a great time!": ["have", "having", "has", "had"],
    "A: Riku, is this your bag? B: No, it isn't (         ). It's Miku`s.": ["my", "me", "I", "mine"],
    "A: Karin, is this David's pencil case? B: Yes, it's (         ) pencil case.": ["he", "she", "him", "his"],
    "A: Whose jacket is this? B: I think it's (         ).": ["they", "them", "their", "theirs"],
    "A: Is this your notebook? B: No, that's (         ). Mine is blue.": ["me", "I", "my", "hers"],
    "A: Whose soccer balls are these? B: They are (         ).": ["our", "we", "us", "ours"],
    "A: Whose desk is this? B: It's (         ) desk. She sits here every day.": ["she", "him", "hers", "her"],
    "A: Is baseball (         ) than soccer, Jamie? B: I think so. Baseball have more complicated rules.": ["so hard", "hard", "hardest", "harder"],
    "A: Am I the (         ) person in our school? B: No. I think Michael is taller.": ["very tall", "taller", "tall", "tallest"],
    "A: Is this test (         ) than the one last week? B: Yes, I think so.": ["easy", "easiest", "more easy", "easier"],
    "A: Who is the (         ) student in your class? B: I think it's Ken.": ["most smart", "more smart", "smart", "smartest"],
    "A: Is winter (         ) than here in your country? B: Yes, and it also snows a lot.": ["coldest", "cold", "so cold", "colder"],
    "A: Which subject is the (         ) for you? B: Math. It's very difficult.": ["more hard", "hard", "harder", "hardest"],
    "A: That mountain is very high! B: Yes, it's the (         ) in Japan.": ["high", "higher", "more high", "highest"],
    "A: Is this bag (         ) than yours? B: Yes, yours is smaller.": ["big", "biggest", "most big", "bigger"],
    "A: That movie was fun! B: Yes, it was the (         ) movie I've seen this year.": ["funnier", "fun", "more fun", "funniest"],
    "A: Is reading (         ) than watching TV? B: Yes, it helps you learn more.": ["good", "more good", "best", "better"],
    "A: Hello, This is Jhonny. Can I speak (         ) Marry? B: Sorry, she's is not here today.": ["as", "on", "in", "to"],
    "A: I would like to live (         ) Osaka. Do you have any apartments available there? B: Yes, we do.": ["it", "of", "for", "in"],
    "A: What time do you usually get (         )? B: Around seven in the morning.": ["on", "with", "to", "up"],
    "A: Do you want to play soccer (         ) school? B: Sure, let's do it!": ["as", "for", "by", "after"],
    "A: I'm going to the park. Do you want to come (         ) me? B: Yes, I'd love to.": ["at", "of", "to", "with"],
    "A: How (         ) is this T-shirt? B: It's 2,000 yen.": ["far", "long", "old", "much"],
    "A: Where is my book? B: It's (         ) the table.": ["after", "up", "of", "under"],
    "A: What's your favorite subject (         ) school? B: I like English.": ["of", "on", "by", "at"],
    "A: What do you usually eat (         ) breakfast? B: I eat eggs and toast.": ["to", "at", "us", "for"],
    "A: I'm hungry. Let's eat something (         ) the café. B: Good idea.": ["on", "this", "to", "at"],
}

eiken4_grammar_sentence_answers = {
    "A: Excuse me. (         ) B: They're $10 each.": ["How are you?", "How do you like my dress?", "how far is it to Tokyo?", "how much are the hamburgers?"],
    "A: Excuse me. (         ) B: It's on the second floor.": ["How are you?", "Do you like coffee?", "Can you swim?", "Where is the shoe store?"],
    "A: (         ) B: Yes, I'd like a cheeseburger and a cola.": ["Where is the bank?", "Do you like pizza?", "How is your mother?", "May I take your order?"],
    "A: (         ) B: No, I go by bus.": ["Can you play tennis?", "Do you want some juice?", "Where's your dog?", "Do you walk to school?"],
    "A: (         ) B: Yes, I do. I play every weekend.": ["Do you like dogs?", "Where is your bag?", "What time is it?", "Do you play soccer?"],
    "A: (         ) B: Sure. I'll help you.": ["Are you hungry?", "Do you like cats?", "Where is my book?", "Can you help me?"],
    "A: (         ) B: I'm from Canada.": ["How old are you?", "What sport do you play?", "Do you have a dog?", "Where are you from?"],
    "A: (         ) B: I usually go to bed at 10 p.m.": ["What's the date today?", "Do you like this song?", "Where do you live?", "What time do you go to bed?"],
    "A: (         ) B: I have two brothers and one sister.": ["Are you OK?", "How old is your father?", "What color is your bag?", "How many siblings do you have?"],
    "A: (         ) B: She's a teacher.": ["Do you want to eat lunch?", "Where is the station?", "Can I borrow your pen?", "What does your mother do?"],
    "A: (         ) Is she in the kitchen? B: No. She's in the living room.": ["I'm looking for my keys", "This is not good.", "I want pudding.", "I'm looking for Nina."],
    "A: (         ) B: Yes, I have two cats.": ["I want to sleep.", "Where is the dog?", "Let's play soccer.", "Do you have any pets?"],
    "A: (         ) B: It's five o'clock.": ["Do you like games?", "Can I go home?", "Where is she?", "What time is it?"],
    "A: (         ) B: Yes, please. I want some tea.": ["Let's play a game.", "Is this your book?", "What do you like?", "Would you like a drink?"],
    "A: (         ) B: He is my math teacher.": ["How old are you?", "Do you like cake?", "Is he your father?", "Who is that man?"],
    "A: (         ) B: It's Monday.": ["Where are you?", "Is your mother here?", "How do you feel?", "What day is it today?"],
    "A: (         ) B: I like soccer and tennis.": ["Where is the ball?", "Who is your teacher?", "Do you know this?", "What sports do you like?"],
    "A: (         ) B: She's cooking dinner.": ["Let's eat cake.", "I want a banana.", "Where is Dad?", "What is Mom doing?"],
    "A: (         ) B: I go to Ivaraki Elementary School.": ["This is my sister.", "Do you like books?", "Who is that?", "Which school do you go to?"],
    "A: (         ) B: I like English the best.": ["What time is it?", "Do you like cats?", "Where are you from?", "What's your favorite subject?"],
    "A: (         ) B: Yes, I can play the piano.": ["I have a toy.", "He is funny.", "Do you go to school?", "Can you play an instrument?"],
    "A: (         ) B: It's my uncle's.": ["This is my chair.", "Do you want juice?", "Where is the ball?", "Whose bag is this?"],
    "A: (         ) B: Because I have a test tomorrow.": ["Do you like math?", "Is it hot today?", "Where are you going?", "Why are you studying now?"],
    "A: (         ) B: No, we have music today.": ["Do you like lunch?", "Is it Monday?", "Where is your teacher?", "Do we have art class today?"],
    "A: (         ) B: Yes, let's go.": ["I'm tired.", "Where's your book?", "Can I sit here?", "Shall we play outside?"],
    "A: Oh no! My bicycle is broken. (         ) B: Sure. I will use my car today anyway.": ["Is this real?", "Do you want money?", "Is this a bicycle?", "Can I use yours?"],
    "A: Oh no! I left my homework at home. (         ) B: Sure. I can show you mine.": ["Do you have a dog?", "Can you go home?", "Where is your school?", "Can I look at yours?"],
    "A: I'm really hungry. (         ) B: OK. Let's go to the cafe.": ["Can I go home?", "What time is it?", "Do you like music?", "Shall we get something to eat?"],
    "A: I can't carry this bag. (         ) B: No problem. I'll help you.": ["Where is the school?", "Can I borrow it?", "Do you want money?", "Can you carry it for me?"],
    "A: I don't have a pencil. (         ) B: Yes, I have two. Here you go.": ["What is this?", "Do you like books?", "Can I play with you?", "Can I borrow one?"],
    "A: My computer isn't working. (         ) B: OK. Let me take a look.": ["Is this yours?", "Do you need a break?", "Shall we watch a movie?", "Can you help me fix it?"],
    "A: I feel a little sick. (         ) B: Yes. Let's go to the nurse.": ["Is this your bag?", "Where is the school?", "Do you like math?", "Can we go to the nurse's office?"],
    "A: I want to play soccer, but I don't have a ball. (         ) B: Sure. I brought mine.": ["Do you like music?", "Where is your team?", "Is this your dog?", "Can I use your ball?"],
    "A: My phone is dead. (         ) B: Of course. Here it is.": ["Do you like dogs?", "Is it sunny today?", "Can you swim?", "Can I borrow your charger?"],
    "A: I forgot my lunch today. (         ) B: Sure. You can have half of mine.": ["Do you want to play?", "Where is the store?", "What time is it?", "Can I have some of yours?"],
    "A: I can't open this jar. (         ) B: Sure, let me do it.": ["What do you want?", "Do you like candy?", "Is this for me?", "Can you open it for me?"],
    "A: I dropped my book into the water. (         ) B: Okay. I have an extra one. You can use it.": ["Do you like books?", "Where is the pen?", "Is this new?", "Can I borrow yours?"],
    "A: I don't know the answer to this question. (         ) B: OK. I'll explain it to you.": ["Can we go home?", "Do you have a cat?", "Is this math?", "Can you help me?"],
    "A: I forgot how to get to the library. (         ) B: No problem. I'll show you.": ["Do you like books?", "Is that your mom?", "Where is your house?", "Can you tell me the way?"],
    "A: My hands are dirty. (         ) B: OK. Here's some soap.": ["Is this lunch?", "Do you want money?", "Can I sit here?", "Can I wash them here?"],
    "A: Mom, I finished my homework. B: (         ) You can play soccer now.": ["look at me now.", "be careful.", "That is true.", "Good job."],
    "A: I cleaned my room, Mom. B: (         ) Now you can watch TV.": ["Come here now.", "It's not good.", "Try harder.", "Well done!"],
    "A: I helped my little brother with his homework. B: (         )": ["Not now.", "I'm tired.", "Why?", "That's nice of you."],
    "A: I got an A on my English test! B: (         ) I'm proud of you.": ["Don't talk.", "Let's go now.", "Sit down.", "That's great!"],
    "A: I made this card for you, Dad. B: (         )": ["Put it away.", "Go outside.", "Wash your hands.", "That's so sweet."],
    "A: I practiced the piano for two hours and learned a new song. B: (         ) Keep it up!": ["That is boring.", "Not again.", "Do something fun.", "Good for you!"],
    "A: I washed the dishes after dinner. B: (         ) You helped a lot.": ["Go to bed now.", "Clean your room.", "That is here.", "Thank you."],
    "A: I won the soccer game! B: (         ) You must be happy.": ["I am sleepy.", "Don't say that.", "Go home now.", "Congratulations!"],
    "A: I read three books last week. B: (         ) I'm impressed.": ["Go outside now.", "Not now.", "Why books?", "That's a lot!"],
    "A: I walked the dog this morning. B: (         ) He looked happy.": ["Go sit down.", "That is my dog.", "Play with me.", "Nice job."],
    "A: I finished cleaning the bathroom. B: (         ) Let's have some ice cream.": ["Now wash your face.", "It was dirty.", "That is serious.", "Great work!"],
    "A: I helped Grandma with dinner. B: (         ) She must be happy.": ["Do your homework.", "No, thanks.", "It is time.", "That was nice of you."],
    "A: I studied all morning. B: (         ) Let's take a break.": ["That is where I am.", "Go now.", "Time to play.", "You worked very hard."],
    "A: I helped my friend carry her bag. B: (         ) That was very kind.": ["She is weak.", "Why did you?", "Do it again.", "You did a good thing."],
    "A: How many friends came to your birthday party? B: (         )": ["More than five hours.", "I'm comming to the party.", "see you later.", "About 40."],
    "A: What time does the movie start? B: (         )": ["I like that actor.", "Let's eat popcorn.", "Not really.", "At 7 o'clock."],
    "A: Where is your little sister now? B: (         )": ["She likes cats.", "He is at school.", "Yes, please.", "She's in the kitchen."],
    "A: How was your weekend? B: (         )": ["I like dogs.", "It is Monday.", "Not much.", "It was fun."],
    "A: Why are you running? B: (         )": ["The sky is blue.", "My name is Ken.", "Let's go shopping.", "I'm late for school."],
    "A: Who is that girl with the red hat? B: (         )": ["I like her shoes.", "She goes fast.", "Let's go home.", "She's my cousin."],
    "A: When is your piano lesson? B: (         )": ["I like music.", "At the music room.", "It is brown.", "At 4 p.m. today."],
    "A: What are you doing now? B: (         )": ["I like pizza.", "I want to go.", "My name is Mika.", "I'm reading a book."],
    "A: How do you go to school? B: (         )": ["I like English.", "This is fun.", "Not today.", "By bicycle."],
    "A: How was the weather yesterday? B: (         )": ["It is math time.", "I'm happy now.", "Not very much.", "It was sunny."],
    "A: What do you want for your birthday? B: (         )": ["Not that one.", "Where is she?", "Let's eat cake.", "A new game."],
    "A: How often do you play video games? B: (         )": ["With my brother.", "We are happy.", "Go ahead.", "Almost every day."],
    "A: Where did you buy that T-shirt? B: (         )": ["It is blue.", "In the morning.", "At 8 o'clock.", "At the mall."],
    "A: How long did you study last night? B: (         )": ["In the box.", "At 9 o'clock.", "I ate dinner.", "For two hours."],
    "A: Who's your English teacher? B: (         )": ["I like apples.", "I want to read.", "Not this one.", "Mr. Smith."],
    "A: What time do you usually get up? B: (         )": ["I have a cat.", "It is green.", "No, thanks.", "Around 6:30." ],
    "A: Do you want to go to the amusement park today? B: Sorry, I have to help repair my fathers car. (         )": ["There is a smell here.", "Finally I can play games.", "This is for me.", "Thanks for asking."],
    "A: Do you want to come to my house this weekend? B: I have to visit my grandmother. (         )": ["I want new shoes.", "This bag is heavy.", "It is my cat.", "Maybe next time."],
    "A: Let's play basketball after school. B: I have music practice then. (         )": ["There is a tree.", "He is a singer.", "This is not good.", "Sorry about that."],
    "A: Do you want to go swimming tomorrow? B: I have a cold. (         )": ["I need a pencil.", "That is a dog.", "Let's eat dinner.", "So I can't go."],
    "A: Let's go hiking this Saturday. B: I'll be out of town. (         )": ["You are right.", "This is fast.", "Open the window.", "Maybe next week."],
    "A: Do you want to play video games now? B: I have homework to finish. (         )": ["I like fish.", "There are many.", "It is blue.", "Maybe later."],
    "A: Want to go shopping after lunch? B: I have to clean my room. (         )": ["This is for my dad.", "Not this one.", "Be careful.", "Thanks anyway."],
    "A: Do you want to join our soccer team? B: I have no time for that. (         )": ["There is a car.", "Where is it?", "He is running.", "But thank you."],
    "A: Let's go watch a movie tonight. B: I have to help my mom. (         )": ["It is hot today.", "I like movies.", "She is nice.", "Maybe another time."],
    "A: Want to visit the zoo this weekend? B: I already have plans. (         )": ["She is not here.", "It is a tiger.", "Close the door.", "But thanks for inviting me."],
    "A: Let's go to the park now. B: I'm waiting for a delivery. (         )": ["He has a dog.", "Look at that!", "It is sunny.", "Sorry, maybe later."],
    "A: Do you want to join us for lunch at the restaurant over there? B: I brought my own food. (         )": ["Where is my spoon?", "I love apples.", "It is Monday.", "But thank you."],
    "A: Let's go ride bikes. B: My bike has a flat tire. (         )": ["This is my friend.", "I like school.", "Go fast.", "So I can't ride it now."],
    "A: Want to go get ice cream? B: I just had some. (         )": ["It is cold.", "That is pink.", "Where is the spoon?", "Maybe next time."],
    "A: Want to go to the library together? B: I have to cook dinner. So (         )": ["He is hungry.", "My book is red.", "eating is good.", "Sorry, not today."],
    "A: Do you want to see a movie this weekend? B: I'll be studying for a test. (         )": ["This is easy.", "That is a desk.", "I like snacks.", "But maybe next time."],
    "A: Who can run faster, you are Keita? B: (         )": ["Don't worry.", "Right away.", "Nothing more.", "I can."],
    "A: Who can sing better, you or your sister? B: (         )": ["Let me help.", "That is mine.", "Not right now.", "She can."],
    "A: Who ate the last cookie? B: (         )": ["It is good.", "Maybe later.", "The airplane.", "Ken did."],
    "A: Who is taller, you or your brother? B: (         )": ["See you soon.", "Don't be late.", "Be quiet.", "He is."],
    "A: Who studies harder, you or Emi? B: (         )": ["Look at this.", "It's too late.", "That's funny.", "She does."],
    "A: Who goes to bed earlier, you or Lisa? B: (         )": ["Come here.", "Where is it?", "I see it.", "Lisa does."],
    "A: Who made this cake, you or your mom? B: (         )": ["That's easy.", "We are friends.", "Over there.", "She did."],
    "A: Who is better at soccer, you or Ken? B: (         )": ["Try again.", "No, thank you.", "I don't think so.", "Ken is."],
    "A: Who has more books, you or Meg? B: (         )": ["It's not far.", "Take your bag.", "Be careful.", "I do."],
    "A: Who got a higher score, you or Yuki? B: (         )": ["Wait a minute.", "Go straight.", "It is old.", "Yuki did."],
    "A: Who likes math more, you or Ken? B: (         )": ["Do your best.", "It's cold today.", "No way.", "He does."],
}

raw_eiken4_sentence_order = {
    "教室は休憩の間とてもさわがしかったです。(         ) the break.": ["the classroom", "was", "very", "noisy", "during"],
    "彼は週末にバイクで買い物へ行くのが好きです。(         ) to go shopping.": ["he", "likes", "to", "ride", "his bike"],
    "私の父は病院で働いています。(         ) at the hospital.": ["my", "father", "works", "as", "a doctor"],
    "彼女は図書館で本を読むのが好きです。(         ) library.": ["she", "enjoys", "reading", "books", "at the"],
    "彼らは毎週土曜日にサッカーをします。(         ) Saturday.": ["they", "play", "soccer", "together", "every"],
    "私は家族と一緒に夕食を作りました。(         ) my family.": ["I", "made", "dinner", "together", "with"],
    "彼の新しいペットはとてもかわいいです。(         ) cute.": ["his", "new", "pet", "is", "very"],
    "私の兄は友達とゲームをします。(         ) with his friends.": ["my", "brother", "plays", "video", "games"],
    "私たちは今朝、早く起きました。(         ) this morning.": ["we", "woke", "up", "very", "early"],
    "彼女は美術館で絵を見るのが好きです。(         ) in the museum.": ["she", "loves", "looking", "at", "paintings"],
    "彼は雨の日に傘を使います。(         ) on rainy days.": ["he", "always", "uses", "his", "umbrella"],
    "彼女は毎朝コーヒーを飲みます。(         ).": ["she", "drinks", "coffee", "every", "morning"],
    "私たちは週末に公園へ行きました。(         ) the weekend.": ["we", "went", "to", "the park", "during"],
    "彼は夜音楽を聴きます。(         ) night.": ["he", "listens", "to", "music", "at"],
    "私は新しい本を読み始めました。(         ) book.": ["I", "started", "reading", "a", "new"],
    "彼らはよく図書館で勉強します。(         ) library.": ["they", "often", "study", "at", "the"],
    "その犬はとても速く走れます。(         ) fast.": ["the", "dog", "can", "run", "very"],
    "私の母はとても料理が上手です。(         ) cook.": ["my", "mother", "is", "a", "great"],
    "彼はたいてい朝にジョギングをします。(         ) in the morning.": ["he", "usually", "goes", "jogging", "early"],
    "彼女は毎日お弁当を作ります。(         ) every day.": ["she", "makes", "a", "lunch", "box"],
    "彼らはいつも夏にキャンプに行きます。(         ) in summer.": ["they", "always", "go", "camping", "together"],
    "父は車を運転して会社に行きます。(         ) to work.": ["my", "father", "drives", "his", "car"],
    "私はよく友達と遊びます。(         ) friends.": ["I", "often", "play", "with", "my"],
    "彼女はかわいい猫を飼っています。(         ) at home.": ["she", "has", "a", "cute", "cat"],
    "私たちは家の掃除をしました。(         ) the house.": ["we", "cleaned", "up", "all", "around"],
    "私は昨日新しい服を買いました。(         ) yesterday.": ["I", "bought", "some", "new", "clothes"],
    "母は毎日花に水をやります。(         ) every morning.": ["my", "mother", "waters", "the", "flowers"],
    "彼らはパーティーでダンスを楽しみました。(         ) at the party.": ["they", "enjoyed", "dancing", "a", "lot"],
    "彼は昼食にサンドイッチを食べました。(         ) lunch.": ["he", "ate", "a", "sandwich", "for"],
    "私の姉は自分の部屋で本を読みます。(         ) her room.": ["my", "sister", "reads", "books", "in"],
    "彼は週末に魚を釣るのが好きです。(         ) weekends.": ["he", "likes", "to", "fish", "on"],
    "私たちは毎朝早く起きます。(         ) morning.": ["we", "wake", "up", "early", "every"],
    "彼女は昼食後に散歩します。(         ) after lunch.": ["she", "goes", "for", "a", "walk"],
    "その男の子はいつもとても親切です。(         ) to everyone.": ["the", "boy", "is", "always", "kind"],
    "私は昨日また友達に会いました。(         ) yesterday.": ["I", "met", "my", "friend", "again"],
    "彼は夜にテレビを見ます。(         ).": ["he", "watches", "TV", "every", "night"],
    "私の祖母は私たちのためにケーキを作ります。(         ) for us.": ["my", "grandmother", "makes", "delicious", "cakes"],
    "彼らは昨夜映画を楽しみました。(         ) last night.": ["they", "enjoyed", "watching", "a", "movie"],
    "私は兄と一緒にゲームをしました。(         ) with my brother.": ["I", "played", "video", "games", "together"],
    "友達と私は一緒にサッカーをしました。My friends (         ).": ["and", "I", "played", "soccer", "together"],
    "彼女はいつもとても遅く寝ます。She always (         ).": ["goes", "to", "bed", "very", "late"],
    "私の兄はテレビゲームをするのが好きです。My brother (         ).": ["likes", "to", "play", "video", "games"],
    "彼らはよくあのモールに買い物に行きます。They often (         ).": ["go", "shopping", "at", "that", "mall"],
    "私の両親は今テレビを見ています。My parents (         ).": ["are", "watching", "TV", "right", "now"],
    "朝には朝食と牛乳を飲みます。In the morning, (         ).": ["I", "drink", "milk", "with", "breakfast"],
    "私たちは日曜日に動物園に行きます。On Sundays, we (         ).": ["go", "to", "the", "zoo", "together"],
    "夕食の後、私たちは短い散歩をします。After dinner, (         ).": ["we", "take", "a", "short", "walk"],
    "夏には私は毎日プールで泳ぎます。In summer, I (         ).": ["swim", "in", "the", "pool", "daily"],
    "彼女の弟は自転車を上手に乗れます。Her little brother (         ).": ["can", "ride", "a", "bicycle", "well"],
    "学校では私たちは面白いことを多く学びます。At school, (         ).": ["we", "learn", "many", "interesting", "things"],
    "私のおじは大学で英語を教えています。My uncle (         ).": ["teaches", "English", "at", "a", "university"],
    "公園では子供たちがボールで遊んでいます。In the park, (         ).": ["children", "are", "playing", "with", "balls"],
    "夜には彼は寝る前に本を読みます。At night, he (         ).": ["reads", "a", "book", "before", "bed"],
    "妹は面白いアニメを見ています。My little sister (         ).": ["is", "watching", "a", "funny", "cartoon"],
    "私のいとこは動物の絵を描くのが得意です。My cousin (         ).": ["is", "good", "at", "drawing", "animals"],
    "祖母は私のためにおいしいクッキーを作ってくれます。My grandma (         ).": ["makes", "delicious", "cookies", "for", "me"],
    "あなたの弟は週末にサッカーをしますか。Does your brother (         )?": ["play", "soccer", "on", "the", "weekend"],
    "あなたは昨夜何を食べましたか。What did (         )?": ["you", "eat", "for", "dinner", "yesterday"],
    "あなたの母はどこで働いていますか。Where does (         )?": ["your", "mother", "work", "every", "day"],
    "昨夜の映画は面白かったですか。Was the movie (         )?": ["you", "watched", "last", "night", "funny"],
    "あなたたちは何時に家に帰りましたか。What time (         )?": ["did", "you", "get", "back", "home"],
    "彼らはほうかごどこで英語を勉強しますか。Where do (         )?": ["they", "study", "English", "after", "school"],
    "あなたの兄はたまに魚を食べていますか。Does your brother (         )?": ["like", "to", "eat", "fish", "sometimes"],
    "朝に学校は何時に始まりますか。What time (         )?": ["does", "school", "start", "in", "morning"],
    "彼は誰と一緒に住んでいますか。Who does (         )?": ["he", "live", "with", "at", "home"],
    "彼女は夕食後に何をしますか。What does (         )?": ["she", "do", "after", "eating", "dinner"],
    "猫は今どこで寝ていますか。Where is (         )?": ["the", "cat", "sleeping", "right", "now"],
    "彼はお店で何を買いましたか。What did (         )?": ["he", "buy", "at", "the", "store"],
    "あなたのおばあさんはどこに住んでいますか。Where does (         )?": ["your", "grandmother", "live", "these", "days"],
    "あなたたちは休みに何をしましたか。What did (         )?": ["you", "do", "during", "the", "holiday"],
    "彼は昨日新しい靴を買いました。(         ).": ["he", "bought", "new", "shoes", "yesterday"],
    "私たちは毎週公園で遊びます。(         ).": ["we", "play", "in", "the", "park"],
    "その犬はとても速く走ります。(         ).": ["the", "dog", "runs", "very", "fast"],
    "彼女はピアノを上手に弾きます。(         ).": ["she", "plays", "the", "piano", "well"],
    "彼の母は看護師です。(         ).": ["his", "mother", "is", "a", "nurse"],
    "私の兄は夜に宿題をします。(         ).": ["my", "brother", "does", "his", "homework"],
    "私たちは海へ行きました。(         ).": ["we", "went", "to", "the", "beach"],
    "その男の子は野球が大好きです。(         ).": ["the", "boy", "loves", "playing", "baseball"],
    "私は毎朝ジョギングをします。(         ).": ["I", "go", "jogging", "every", "morning"],
    "彼女はときどき英語の本を読みます。(         ).": ["she", "sometimes", "reads", "English", "books"],
    "私の祖父は毎日新聞を読みます。(         ).": ["my", "grandfather", "reads", "the newspaper", "every day"],
    "彼らは友達とサッカーをしました。(         ).": ["they", "played", "soccer", "with", "friends"],
    "私は昨日おばさんと話しました。(         ).": ["I", "talked", "to", "my aunt", "last night"],
    "彼は図書館で本を借りました。(         ).": ["he", "borrowed", "a book", "at the", "library"],
    "私の姉は東京に住んでいます。(         ).": ["my", "sister", "lives", "in", "Tokyo"],
    "私たちはその店で昼ごはんを食べました。(         ).": ["we", "ate", "lunch", "at", "the restaurant"],
    "彼女は朝にシャワーを浴びます。(         ).": ["she", "takes", "a", "shower", "every morning"],
    "私は先生に質問しました。(         ).": ["I", "asked", "the", "teacher", "a question"],
    "彼らは週に一回英語を学びます。(         ).": ["they", "study", "English", "once", "a week"],
    "彼は今日とても早く起きました。(         ).": ["he", "woke", "up", "very", "early today"],
    "彼はどこでその本を読みましたか。(         )?": ["where", "did", "he", "read", "that book"],
    "あなたは昨日どこに行きましたか。(         )?": ["where", "did", "you", "go", "yesterday"],
    "彼女は今日何を食べましたか。(         )?": ["what", "did", "she", "eat", "today"],
    "あなたは英語を上手に話せますか。(         )?": ["can", "you", "speak", "English", "well"],
    "彼はピアノを弾けますか。(         )?": ["can", "he", "play", "the", "piano"],
    "あなたはどこで泳ぎましたか。(         )?": ["where", "did", "you", "go", "swimming"],
    "誰がその映画を見ましたか。(         )?": ["who", "watched", "the", "new", "movie"],
    "彼女は昨日どこで勉強しましたか。(         )?": ["where", "did", "she", "study", "yesterday"],
    "彼らは公園で遊びましたか。(         )?": ["did", "they", "play", "at", "the park"],
    "あなたのお母さんは先生ですか。(         )?": ["is", "your", "mother", "a", "teacher"],
    "どれがあなたの自転車ですか。(         )?": ["which", "one", "is", "your", "bike"],
    "あなたは朝ごはんを食べましたか。(         )?": ["did", "you", "eat", "breakfast", "today"],
    "彼は何時に起きましたか。(         )?": ["what", "time", "did", "he", "wake up"],
    "あなたも犬が好きですか。(         )?": ["do", "you", "like", "dogs", "too"],
    "誰がその手紙を書いて送りましたか。(         )?": ["who", "wrote", "and sent", "this", "letter?"],
    "彼らは何を話していましたか。(         )?": ["what", "were", "they", "talking", "about"],
    "それは本当に必要ですか。(         )?": ["is", "that", "really", "so", "important"],
    "あなたは土曜日に働きますか。(         )?": ["do", "you", "work", "on", "Saturday"],
    "その女の子は誰ですか。(         )?": ["who", "is", "that", "little", "girl"],
    "彼は弟と同じくらい背が高いです。He is (         ).": ["as", "tall", "as", "his", "brother"],
    "このバッグはあのバッグと同じくらい高いです。This bag is (         ).": ["as", "expensive", "as", "that", "bag"],
    "彼女は猫と同じくらい静かです。She is (         ).": ["as", "quiet", "as", "a", "cat"],
    "この川はあの川と同じくらい長いです。This river is (         ).": ["as", "long", "as", "that", "river"],
    "彼の部屋は私の部屋と同じくらいきれいです。His room is (         ).": ["as", "clean", "as", "my", "room"],
    "彼は明日学校へ行きますか。(         )?": ["will", "he", "go to", "school", "tomorrow"],
    "あなたは今日の午後図書館に行きますか。(         )?": ["will", "you", "go to the", "library", "this afternoon"],
    "彼らは来週サッカーをしますか。(         )?": ["will", "they", "play", "soccer", "next week"],
    "彼女はその本を読みますか。(         )?": ["will", "she", "read", "that", "book"],
    "私たちは今夜映画を見ますか。(         ) tonight?": ["will", "we", "watch", "a", "movie"],
    "その箱を開けないでください。(         ).": ["please", "don't", "open", "that", "box"],
    "遅くまで起きていないでください。(         ).": ["don't", "stay", "up", "too", "late"],
    "壁に絵を描かないでください。(         ) please.": ["don't", "draw", "pictures", "on", "walls"],
    "猫にチョコレートをあげないでください。Please, (         ).": ["don't", "give", "chocolate", "to", "cats"],
    "どうやってこの問題を解けますか。(         ) problem?": ["how", "can", "I", "solve", "this"],
    "どうやって駅に行けますか。(         ) the station?": ["how", "can", "I", "get", "to"],
    "どうやって英語を上達できますか。(         )?": ["how", "can", "I", "improve", "my English"],
    "どうやってこのパズルを完成させられますか。(         ) puzzle?": ["how", "can", "I", "finish", "this"],
    "私は夏休みを楽しみにしています。(         ) summer vacation.": ["I", "am", "looking", "forward", "to"],
    "彼女は新しい映画を見るのを楽しみにしています。(         ) watching the new movie.": ["she", "is", "looking", "forward", "to"],
    "私たちは来週の旅行を楽しみにしています。(         ) the trip next week.": ["we", "are", "looking", "forward", "to"],
    "彼はパーティーを楽しみにしています。(         ) the party.": ["he", "is", "looking", "forward", "to"],
    "この本を借りてもよろしいですか。(         )?": ["may", "I", "borrow", "this", "book"],
    "トイレに行ってもよろしいですか。(         )?": ["may", "I", "go", "to", "the bathroom"],
    "窓を開けてもよろしいですか。(         )?": ["may", "I", "open", "the", "window"],
    "ここに座ってもよろしいですか。(         )?": ["may", "I", "sit", "here", "please"],
    "あなたはサッカーが得意ですか。(         )?": ["are", "you", "good", "at", "soccer"],
    "彼はピアノが得意ですか。(         )?": ["is", "he", "good", "at", "piano"],
    "彼女は絵を描くのが得意ですか。(         )?": ["is", "she", "good", "at", "drawing"],
    "あなたたちは英語が得意ですか。(         )?": ["are", "you", "good", "at", "English"],
    "彼らは料理が得意ですか。(         )?": ["are", "they", "good", "at", "cooking"],
    "私は明日図書館へ行くつもりです。(         ) tomorrow.": ["I", "am", "going", "to", "the library"],
    "彼は来週映画を見るつもりです。(         ) movie.": ["he", "is", "going", "to", "watch a"],
    "私たちは日曜日にサッカーをする予定です。(         ) tomorrow.": ["we", "are", "going", "to", "play soccer"],
    "彼女は夕食を作るつもりです。(         ).": ["she", "is", "going", "to", "make dinner"],
    "彼らは公園でピクニックをする予定です。(         ) at the park.": ["they", "are", "going", "to", "have a picnic"],
    "この都市はその美しい庭園で有名です。(         ).": ["this", "city", "is", "famous", "for its gardens"],
    "彼はすばらしい音楽で有名です。(         ).": ["he", "is", "famous", "for", "his music"],
    "そのレストランはおいしい料理で有名です。(         ) its food.": ["the", "restaurant", "is", "famous", "for"],
    "彼女はその本で有名になりました。(         ).": ["she", "became", "famous", "for", "that book"],
    "日本はアニメで有名です。(         ).": ["Japan", "is", "famous", "for", "anime"],
}


eiken4_sentence_order = {
    add_furigana(key): value for key, value in raw_eiken4_sentence_order.items()
}
