from .models import Test, Question, MaxScore
from django.db.models import Sum

def get_profile_assets(total_max_scores):

    assets = {
        0: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_19_1.mp3", "image": "https://storage.googleapis.com/profile_assets/a-crying.jpeg", "text": "泣くことしかできない生まれたての赤ちゃんです", "english_text" : "are a baby that can do nothing but cry", "audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_19_1.mp3"},
        1: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_04_1.mp3", "image": "https://storage.googleapis.com/profile_assets/b-mamaivar.jpeg", "text": "MamaとIvar殿しか言えない赤ちゃんです", "english_text" : "are a baby that can only say Mama and Ivar", "audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_31_1.mp3"},
        2: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_11_1.mp3", "image": "https://storage.googleapis.com/profile_assets/c-walkingwalking.jpeg", "text": "なんとなく歩けるようになった子供だ", "english_text" : "have just learned how to walk", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_52_45_1.mp3"},
        3: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_19_1.mp3", "image": "https://storage.googleapis.com/profile_assets/crayon.jpeg", "text": "お描きできるようになった", "english_text" : "have just learned how to draw pictures", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_40_45_1.mp3"},
        4: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_30_1.mp3", "image": "https://storage.googleapis.com/profile_assets/d-read.jpeg", "text": "絵本を読めるようになった", "english_text" : "have just learned how to read picture books", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_52_53_1.mp3"},
        5: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_01_1.mp3", "image": "https://storage.googleapis.com/profile_assets/math.png", "text": "算数できるようになった", "english_text" : "have just learned how to do simple math", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_41_52_1.mp3"},
        6: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_17_1.mp3", "image": "https://storage.googleapis.com/profile_assets/boxing_boy.jpeg", "text": "パンチできるようになったけど、あまり威力ないな", "english_text" : "have just learned how to punch, still pretty weak though", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_43_39_1.mp3"},
        7: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_25_1.mp3", "image": "https://storage.googleapis.com/profile_assets/e-ama.jpeg", "text": "自分が強いと思ってるけど、実はまだまだあまい！", "english_text" : "think you are strong but the truth is you are still naive", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_53_00_1.mp3"},
        8: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_17_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_25_2.mp3", "image": "https://storage.googleapis.com/profile_assets/1bicycle.png", "text": "自転車を乗れるようになった", "english_text": "have learned how to ride a bicycle"},
        9: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_42_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_50_2.mp3", "image": "https://storage.googleapis.com/profile_assets/2gym.jpg", "text": "ジム通い始めてちょっとムキムキになった", "english_text": "have started to go to a gym and managed to build some muscle"},
        10: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_17_08_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_17_36_2.mp3", "image": "https://storage.googleapis.com/profile_assets/3ice.jpg", "text": "氷の力を持っている", "english_text": "have the power of ice"},
        11: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_34_1.mp3", "image": "https://storage.googleapis.com/profile_assets/rocklift.png", "text": "５０キロの岩持ち上げれるようになった", "english_text" : "have just become able to lift a 50kg stone", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_44_57_1.mp3"},
        12: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_46_02_1.mp3", "image": "https://storage.googleapis.com/profile_assets/ninja.png", "text": "アニメ見すぎて、自分が忍者だと思い込んでしまった", "english_text" : "watched too much anime and now you think you are a ninja", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_46_02_1.mp3"},
        13: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_18_1.mp3", "image": "https://storage.googleapis.com/profile_assets/f-arm.jpeg", "text": "弱い先生ならたまに腕相撲で勝てる", "english_text" : "can beat weak teachers in armwrestling", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_54_58_1.mp3"},
        14: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_35_1.mp3", "image": "https://storage.googleapis.com/profile_assets/g-fire.jpeg", "text": "一般的な少年として口から火出せる", "english_text" : "can breathe fire like most normal boys can", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_56_57_1.mp3"},
        15: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_46_1.mp3", "image": "https://storage.googleapis.com/profile_assets/rock_smash.png", "text": "パンチで岩を壊せる", "english_text" : "can destroy rocks with your punches", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_48_47_1.mp3"},
        16: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_18_06_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_18_11_2.mp3", "image": "https://storage.googleapis.com/profile_assets/4scooter.png", "text": "原付を乗れるようになった", "english_text": "have learned how to ride a scooter"},
        17: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_19_38_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_19_45_2.mp3", "image": "https://storage.googleapis.com/profile_assets/5tree.png", "text": "木を蹴り一発で破壊できる", "english_text": "can destroy "},
        18: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_05_1.mp3", "image": "https://storage.googleapis.com/profile_assets/soap_bubbles.png", "text": "シャボン玉攻撃できるようになった", "english_text" : "can now use soap bubble attacks", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_49_58_1.mp3"},
        19: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_20_28_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_20_34_2.mp3", "image": "https://storage.googleapis.com/profile_assets/6animals.jpg", "text": "動物をコントロールできるようになった", "english_text": "are able to control animals"},
        20: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_17_1.mp3", "image": "https://storage.googleapis.com/profile_assets/h-grown.jpeg", "text": "一般的な大人です。握力５００キロ", "english_text" : "are a normal adult with a grip strenght of 500kg", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_57_34_1.mp3"},
        21: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_14_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_19_2.mp3", "image": "https://storage.googleapis.com/profile_assets/7motorcycle.png", "text": "普通のバイクを乗れるようになった", "english_text": "are able to ride a regular motorcycle"},
        22: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_44_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_49_2.mp3", "image": "https://storage.googleapis.com/profile_assets/8drive.png", "text": "車の運転をできるになった", "english_text": "are able to drive a car"},
        23: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_07_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_11_2.mp3", "image": "https://storage.googleapis.com/profile_assets/9money.jpg", "text": "会社作って大金持ちになった", "english_text": "made a company and became filthy rich"},
        24: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_43_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_50_2.mp3", "image": "https://storage.googleapis.com/profile_assets/10airplane.jpg", "text": "飛行機を操縦できるようになった", "english_text": "have learned how to fly an airplane"},
        25: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_07_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_26_2.mp3", "image": "https://storage.googleapis.com/profile_assets/10earthquake.jpg", "text": "自身を作る力を手に入れた", "english_text": "have gained the power to create earth quakes"},

        26: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_28_1.mp3", "image": "https://storage.googleapis.com/profile_assets/sun.png", "text": "勉強の成果で小さい太陽作れるようになった", "english_text" : "have from your intense studies learned how to make a sun", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_52_29_1.mp3"},
        27: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_41_1.mp3", "image": "https://storage.googleapis.com/profile_assets/firewolf.png", "text": "この可愛いペットを乗れるようになった", "english_text" : "are now able to ride this cute pet", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_57_07_1.mp3"},
        28: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_34_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_38_2.mp3", "image": "https://storage.googleapis.com/profile_assets/11beardman.jpg", "text": "髭の攻撃できるようになった", "english_text": "can attack with your beard"},
        29: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_01_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_07_2.mp3", "image": "https://storage.googleapis.com/profile_assets/12polarbear.jpg", "text": "北極熊を乗っているパラディンになった", "english_text": "are a palading riding a polar bear"},

        30: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_51_1.mp3", "image": "https://storage.googleapis.com/profile_assets/i-mukimuki.jpeg", "text": "ちょっとヒーローぽい存在", "english_text" : "are a bit like a hero now", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_07_09_1.mp3"},
        31: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_56_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_02_2.mp3", "image": "https://storage.googleapis.com/profile_assets/13diamond.jpg", "text": "握力でダイアをつぶせるようになった", "english_text": "are able to crush a diamond with your hands"},
        32: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_22_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_27_2.mp3", "image": "https://storage.googleapis.com/profile_assets/14spaceman.jpg", "text": "宇宙飛行機を操縦できるようになった", "english_text": "are able to fly a space ship"},
        33: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_50_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_54_2.mp3", "image": "https://storage.googleapis.com/profile_assets/15dragon.jpg", "text": "魔法で龍を呼び出すことができる", "english_text": "are able to summon a dragon with magic"},

        34: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_02_1.mp3", "image": "https://storage.googleapis.com/profile_assets/j-electricity.jpeg", "text": "雷の力を持つ本物のヒーロー", "english_text" : "are now a true hero with the power of lightning", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_58_51_1.mp3"},
        35: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_21_1.mp3", "image": "https://storage.googleapis.com/profile_assets/blackhole.png", "text": "勉強の成果で小さいブラックホール作れるようになった", "english_text" : "have from your intense studies learned how to make a black hole", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_58_39_1.mp3"},
        36: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_33_1.mp3", "image": "https://storage.googleapis.com/profile_assets/k-superhero.jpeg", "text": "雷とレーザーの力を持つ本物のヒーロー", "english_text" : "are a true hero with the power of lightning and lazer", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_00_03_1.mp3"},
        37: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_42_1.mp3", "image": "https://storage.googleapis.com/profile_assets/beardman.png", "text": "髭生やしてさらに強くなった", "english_text" : "have gained even more power by growing your beard", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_59_54_1.mp3"},
        38: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_12_45_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_12_56_2.mp3", "image": "https://storage.googleapis.com/profile_assets/16moon.jpg", "text": "忍術で月を破壊できる", "english_text": "can destroy the moon with ninjutsu"},

        39: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_57_1.mp3", "image": "https://storage.googleapis.com/profile_assets/l-samurai.jpeg", "text": "地球を１秒で破壊できる侍", "english_text" : "are a samurai that can destroy the earth in 1 second", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_04_48_1.mp3"},
        40: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_13_13_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_13_21_2.mp3", "image": "https://storage.googleapis.com/profile_assets/17sun.png", "text": "星を団子の様に食べれる", "english_text": "can eat stars like you eat dango"},

        41: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_08_1.mp3", "image": "https://storage.googleapis.com/profile_assets/neutronstar.png", "text": "普段から朝ごはんに中性子星を食べる", "english_text" : "eat neutronstars for breakfast", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_12_00_40_1.mp3"},
        42: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_14_41_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_14_51_2.mp3", "image": "https://storage.googleapis.com/profile_assets/18antimatter.png", "text": "反物質をつくれるようになった", "english_text": "are able to create antimatter"},
        43: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_21_1.mp3", "image": "https://storage.googleapis.com/profile_assets/blackholedrinker.png", "text": "喉乾いたときブラックホールをストローで飲む", "english_text" : "drink blackholes with a straw whenever you are thirsty", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_12_02_15_1.mp3"},
        44: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_23_48_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_23_57_2.mp3", "image": "https://storage.googleapis.com/profile_assets/19galaxy.png", "text": "掃除機で銀河を吸い取れる", "english_text": "you can suck in galaxies with your vacuum cleaner"},
        45: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_24_21_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_24_31_2.mp3", "image": "https://storage.googleapis.com/profile_assets/20galaxycreator.png", "text": "息するだけで銀河を作れる", "english_text": "can create galaxies by just breathing"},

        46: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_31_1.mp3", "image": "https://storage.googleapis.com/profile_assets/m-uni.jpeg", "text": "宇宙のすべてを１秒で破壊できる存在", "english_text" : "are a being that can destroy the whole universe in 1 second", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_05_21_1.mp3"},
        47: {"english_audio": "https://storage.googleapis.com/ivar_reactions/2024_12_07_19_36_49_1.mp3", "image": "https://storage.googleapis.com/profile_assets/n-ivar.jpg", "text": "このサイトの理解を超えてる存在", "english_text" : "are a being that is beyond the comprehension of this site", "audio": "https://storage.googleapis.com/ivar_reactions/sound13%20(1).mp3"},

    }

    return assets

def get_eiken_pet(total_eiken_scores):

    pets = {
        0: {"image": 'https://storage.googleapis.com/profile_pets/one_cell.png', "text": 'まだ細胞一つしかない生物', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_25_1.mp3', "english_text": 'still only a one celled organism'},
        1: {"image": 'https://storage.googleapis.com/profile_pets/multi_cell.png', "text": '複数の細胞からできている生物', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_35_1.mp3', "english_text": 'an organism made up of multiple cells'},
        2: {"image": 'https://storage.googleapis.com/profile_pets/plancton.png', "text": 'プランクトンまで進化した', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_47_1.mp3', "english_text": 'has evolved into a plancton'},
        3: {"image": 'https://storage.googleapis.com/profile_pets/tiny_fish.png', "text": '少し泳げる小さな魚', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_55_1.mp3', "english_text": 'a tiny fish that can swim a little bit'},
        4: {"image": 'https://storage.googleapis.com/profile_pets/turtle.png', "text": '地上で歩ける亀', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_16_47_1.mp3', "english_text": 'a turtle that can walk on land'},
        5: {"image": 'https://storage.googleapis.com/profile_pets/mouse.png', "text": 'チーズを食べれるネズミ', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_17_16_1.mp3', "english_text": 'a mouse that can eat cheese'},
        6: {"image": 'https://storage.googleapis.com/profile_pets/cookiehamster.png', "text": 'クッキー大好きなハムスター', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_29_31_2.mp3', "english_text": 'a hamster that loves cookies'},
        7: {"image": 'https://storage.googleapis.com/profile_pets/squirel.png', "text": '木を登ってナッツを食べることができるリス', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_17_26_1.mp3', "english_text": 'a squirrel that can climb trees and eat nuts'},
        8: {"image": 'https://storage.googleapis.com/profile_pets/hedge_hog.jpeg', "text": '普通のハリネズミ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_18_19_1.mp3', "english_text": 'a regular hedge hog'},
        9: {"image": 'https://storage.googleapis.com/profile_pets/samuraisloth.png', "text": 'だいぶ動きが遅いなまけもの侍', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_36_00_2.mp3', "english_text": 'a really slow samurai sloth'},
        10: {"image": 'https://storage.googleapis.com/profile_pets/rabbit.png', "text": 'IQ１２０のウサギ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_46_16_1.mp3', "english_text": 'a rabbit with in IQ of 120'},
        11: {"image": 'https://storage.googleapis.com/profile_pets/frog.png', "text": 'イバルの里で修行を受けたカエル', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_22_40_21_1.mp3', "english_text": 'a frog that has been trained in The Village Of Ivar'},
        12: {"image": "https://storage.googleapis.com/profile_pets/1weaponbat.jpg", "text": "色んな武器を風の力で使えるこうもり", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_06_41_2.mp3", "english_text": "a bat that can use various weapons with wind"},
        13: {"image": 'https://storage.googleapis.com/profile_pets/kungfucat.png', "text": '中国拳法得意な猫', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_32_27_2.mp3', "english_text": 'a that is good at kung fu'},
        14: {"image": "https://storage.googleapis.com/profile_pets/1fatkoala.jpg", "text": "IQ２０、体重２００キロのコアラ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_53_2.mp3", "english_text": "a 200kg koala with 20 IQ"},
        15: {"image": "https://storage.googleapis.com/profile_pets/2donkey.jpg", "text": "怒ているロバ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_57_39_2.mp3", "english_text": "an anry donkey"},
        16: {"image": "https://storage.googleapis.com/profile_pets/2woolsheep.jpg", "text": "ウールが多すぎる羊", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_58_39_2.mp3", "english_text": "a sheep with too much wool"},
        17: {"image": "https://storage.googleapis.com/profile_pets/3merecatsniper.jpg", "text": "狙撃兵のミーアキャット", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_59_29_2.mp3", "english_text": "a sniper merecat"},
        18: {"image": "https://storage.googleapis.com/profile_pets/4muscledeer.jpg", "text": "むきむきの鹿", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_00_02_2.mp3", "english_text": "a shredded deer"},
        19: {"image": "https://storage.googleapis.com/profile_pets/5wildboard.jpg", "text": "伝説的な英雄イノシシ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_00_11_2.mp3", "english_text": "a legendary hero wild boar"},
        20: {"image": "https://storage.googleapis.com/profile_pets/6chorusllama.jpg", "text": "人間の歌をカラオケで歌えるラマ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_01_33_2.mp3", "english_text": "a lama that can sing human songs on karaoke"},
        21: {"image": 'https://storage.googleapis.com/profile_pets/lesser_panda.png', "text": 'ちょっとオーラがあるレッサーパンダ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_22_40_44_1.mp3', "english_text": 'a lesser panda with a bit of aura'},
        22: {"image": 'https://storage.googleapis.com/profile_pets/truthbeaver.png', "text": 'どの嘘でも見抜ける真実のビーバー', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_39_31_2.mp3', "english_text": 'a lesser panda with a bit of aura'},
        23: {"image": 'https://storage.googleapis.com/profile_pets/samuraimonkey.png', "text": '六刀流使いの侍さる', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_33_17_2.mp3', "english_text": 'a samurai monkey that uses 6 swords style'},
        24: {"image": 'https://storage.googleapis.com/profile_pets/spiritfox.png', "text": '色んな魔法の儀式で自然を守るきつね', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_36_55_2.mp3', "english_text": 'a for that protects nature with magical rituals'},
        25: {"image": 'https://storage.googleapis.com/profile_pets/goldendog.png', "text": '結構野蛮な犬', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_30_21_2.mp3', "english_text": 'a pretty savage dog'},
        26: {"image": "https://storage.googleapis.com/profile_pets/7stronzebra.jpg", "text": "めがあったらえらい目に合えるしまうま", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_03_46_2.mp3", "english_text": "a zebra you should avoid making eye contact with"},
        27: {"image": "https://storage.googleapis.com/profile_pets/8fastchetah.jpg", "text": "１０００キロの速度で走るチーター", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_04_50_2.mp3", "english_text": "a cheetah that can run 1000km/h"},
        28: {"image": "https://storage.googleapis.com/profile_pets/9legendaryrino.jpg", "text": "伝説的なさいの戦士", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_22_2.mp3", "english_text": "a legendary warrior rhino"},
        29: {"image": "https://storage.googleapis.com/profile_pets/10powerfulbear.jpg", "text": "魔法を使える王様熊", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_44_2.mp3", "english_text": "a king bear with magical powers"},
    }


    return pets

def get_eiken_memories(total_eiken_scores):
    levels = int(total_eiken_scores // 100)

    pets = {
        1: {"image": 'https://storage.googleapis.com/profile_pets/one_cellframe.png', "text": 'まだ細胞一つしかない生物', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_25_1.mp3', "english_text": 'still only a one celled organism'},
        2: {"image": 'https://storage.googleapis.com/profile_pets/multi_cellframe.png', "text": '複数の細胞からできている生物', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_35_1.mp3', "english_text": 'an organism made up of multiple cells'},
        3: {"image": 'https://storage.googleapis.com/profile_pets/planctonframe.png', "text": 'プランクトンまで進化した', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_47_1.mp3', "english_text": 'has evolved into a plancton'},
        4: {"image": 'https://storage.googleapis.com/profile_pets/tiny_fishframe.png', "text": '少し泳げる小さな魚', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_14_55_1.mp3', "english_text": 'a tiny fish that can swim a little bit'},
        5: {"image": 'https://storage.googleapis.com/profile_pets/turtleframe.png', "text": '地上で歩ける亀', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_16_47_1.mp3', "english_text": 'a turtle that can walk on land'},
        6: {"image": 'https://storage.googleapis.com/profile_pets/mouseframe.png', "text": 'チーズを食べれるネズミ', "audio": 'https://storage.googleapis.com/profile_pets/2024_12_23_12_17_16_1.mp3', "english_text": 'a mouse that can eat cheese'},
        7: {"image": 'https://storage.googleapis.com/profile_pets/cookiehamsterframe.png', "text": 'クッキー大好きなハムスター', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_29_31_2.mp3', "english_text": 'a hamster that loves cookies'},
        8: {"image": 'https://storage.googleapis.com/profile_pets/squirelframe.png', "text": '木を登ってナッツを食べることができるリス', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_17_26_1.mp3', "english_text": 'a squirrel that can climb trees and eat nuts'},
        9: {"image": 'https://storage.googleapis.com/profile_pets/hedge_hogframe.png', "text": '普通のハリネズミ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_18_19_1.mp3', "english_text": 'a regular hedge hog'},
        10: {"image": 'https://storage.googleapis.com/profile_pets/samuraislothframe.png', "text": 'だいぶ動きが遅いなまけもの侍', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_36_00_2.mp3', "english_text": 'a really slow samurai sloth'},
        11: {"image": 'https://storage.googleapis.com/profile_pets/rabbitframe.png', "text": 'IQ１２０のウサギ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_19_46_16_1.mp3', "english_text": 'a rabbit with in IQ of 120'},
        12: {"image": 'https://storage.googleapis.com/profile_pets/frogframe.png', "text": 'イバルの里で修行を受けたカエル', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_22_40_21_1.mp3', "english_text": 'a frog that has been trained in The Village Of Ivar'},
        13: {"image": "https://storage.googleapis.com/profile_pets/batframe.png", "text": "色んな武器を風の力で使えるこうもり", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_06_41_2.mp3", "english_text": "a bat that can use various weapons with wind"},
        14: {"image": 'https://storage.googleapis.com/profile_pets/kungfucatframe.png', "text": '中国拳法得意な猫', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_32_27_2.mp3', "english_text": 'a that is good at kung fu'},
        15: {"image": "https://storage.googleapis.com/profile_pets/koalaframe.png", "text": "IQ２０、体重２００キロのコアラ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_53_2.mp3", "english_text": "a 200kg koala with 20 IQ"},
        16: {"image": "https://storage.googleapis.com/profile_pets/donkeyframe.png", "text": "怒ているロバ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_57_39_2.mp3", "english_text": "an anry donkey"},
        17: {"image": "https://storage.googleapis.com/profile_pets/sheepframe.png", "text": "ウールが多すぎる羊", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_58_39_2.mp3", "english_text": "a sheep with too much wool"},
        18: {"image": "https://storage.googleapis.com/profile_pets/merecatframe.png", "text": "狙撃兵のミーアキャット", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_10_59_29_2.mp3", "english_text": "a sniper merecat"},
        19: {"image": "https://storage.googleapis.com/profile_pets/deerframe.png", "text": "むきむきの鹿", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_00_02_2.mp3", "english_text": "a shredded deer"},
        20: {"image": "https://storage.googleapis.com/profile_pets/boarframe.png", "text": "伝説的な英雄イノシシ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_00_11_2.mp3", "english_text": "a legendary hero wild boar"},
        21: {"image": "https://storage.googleapis.com/profile_pets/lamaframe.png", "text": "人間の歌をカラオケで歌えるラマ", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_01_33_2.mp3", "english_text": "a lama that can sing human songs on karaoke"},
        22: {"image": 'https://storage.googleapis.com/profile_pets/lesser_pandaframe.png', "text": 'ちょっとオーラがあるレッサーパンダ', "audio": 'https://storage.googleapis.com/profile_pets/2025_01_13_22_40_44_1.mp3', "english_text": 'a lesser panda with a bit of aura'},
        23: {"image": 'https://storage.googleapis.com/profile_pets/truthbeaverframe.png', "text": 'どの嘘でも見抜ける真実のビーバー', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_39_31_2.mp3', "english_text": 'a lesser panda with a bit of aura'},
        24: {"image": 'https://storage.googleapis.com/profile_pets/samuraimonkeyframe.png', "text": '六刀流使いの侍さる', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_33_17_2.mp3', "english_text": 'a samurai monkey that uses 6 swords style'},
        25: {"image": 'https://storage.googleapis.com/profile_pets/spiritfoxframe.png', "text": '色んな魔法の儀式で自然を守るきつね', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_36_55_2.mp3', "english_text": 'a for that protects nature with magical rituals'},
        26: {"image": 'https://storage.googleapis.com/profile_pets/goldendogframe.png', "text": '結構野蛮な犬', "audio": 'https://storage.googleapis.com/profile_pets/2025_06_23_13_30_21_2.mp3', "english_text": 'a pretty savage dog'},
        27: {"image": "https://storage.googleapis.com/profile_pets/zebraframe.png", "text": "めがあったらえらい目に合えるしまうま", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_03_46_2.mp3", "english_text": "a zebra you should avoid making eye contact with"},
        28: {"image": "https://storage.googleapis.com/profile_pets/cheetahframe.png", "text": "１０００キロの速度で走るチーター", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_04_50_2.mp3", "english_text": "a cheetah that can run 1000km/h"},
        29: {"image": "https://storage.googleapis.com/profile_pets/rhinoframe.png", "text": "伝説的なさいの戦士", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_22_2.mp3", "english_text": "a legendary warrior rhino"},
        30: {"image": "https://storage.googleapis.com/profile_pets/bearframe.png", "text": "魔法を使える王様熊", "audio": "https://storage.googleapis.com/profile_pets/2025_09_01_11_05_44_2.mp3", "english_text": "a king bear with magical powers"},

    }


    result = {level: pets[level] for level in range(1, levels + 1) if level in pets}
    return result

def get_memories(total_max_scores):
    levels = int(total_max_scores // 50)

    memories = {
        1: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_19_1.mp3", "image": "https://storage.googleapis.com/profile_assets/a-baby.png", "text": "泣くことしかできない生まれたての赤ちゃんです", "audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_19_1.mp3"},
        2: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_04_1.mp3", "image": "https://storage.googleapis.com/profile_assets/b-baby.png", "text": "MamaとIvar殿しか言えない赤ちゃんです", "audio": "https://storage.googleapis.com/profile_assets/2024_10_28_13_01_31_1.mp3"},
        3: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_11_1.mp3", "image": "https://storage.googleapis.com/profile_assets/c-walking.png", "text": "なんとなく歩けるようになった子供だ", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_52_45_1.mp3"},
        4: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_19_1.mp3", "image": "https://storage.googleapis.com/profile_assets/drawing_frame.png", "text": "お描きできるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_40_45_1.mp3"},
        5: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_58_30_1.mp3", "image": "https://storage.googleapis.com/profile_assets/d-reading.png", "text": "絵本を読めるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_52_53_1.mp3"},
        6: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_01_1.mp3", "image": "https://storage.googleapis.com/profile_assets/math_frame.png", "text": "算数できるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_41_52_1.mp3"},
        7: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_17_1.mp3", "image": "https://storage.googleapis.com/profile_assets/boxing_frame.png", "text": "パンチできるようになったけど、あまり威力ないな", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_43_39_1.mp3"},
        8: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_25_1.mp3", "image": "https://storage.googleapis.com/profile_assets/e-amai.png", "text": "自分が強いと思ってるけど、実はまだまだあまい！", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_53_00_1.mp3"},
        9: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_17_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_25_2.mp3", "image": "https://storage.googleapis.com/profile_assets/1bicycleframe.png", "text": "自転車を乗れるようになった", "english_text": "have learned how to ride a bicycle"},
        10: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_42_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_16_50_2.mp3", "image": "https://storage.googleapis.com/profile_assets/2gymframe.png", "text": "ジム通い始めてちょっとムキムキになった", "english_text": "have started to go to a gym and managed to build some muscle"},
        11: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_17_08_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_17_36_2.mp3", "image": "https://storage.googleapis.com/profile_assets/3iceframe.png", "text": "氷の力を持っている", "english_text": "have the power of ice"},
        12: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_18_59_34_1.mp3", "image": "https://storage.googleapis.com/profile_assets/rock_frame.png", "text": "５０キロの岩持ち上げれるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_44_57_1.mp3"},
        13: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_46_02_1.mp3", "image": "https://storage.googleapis.com/profile_assets/ninja_frame.png", "text": "アニメ見すぎて、自分が忍者だと思い込んでしまった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_46_02_1.mp3"},
        14: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_18_1.mp3", "image": "https://storage.googleapis.com/profile_assets/f-armwrestler.png", "text": "弱い先生ならたまに腕相撲で勝てる", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_54_58_1.mp3"},
        15: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_35_1.mp3", "image": "https://storage.googleapis.com/profile_assets/g-flames.png", "text": "一般的な少年として口から火出せる", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_56_57_1.mp3"},
        16: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_00_46_1.mp3", "image": "https://storage.googleapis.com/profile_assets/rocksmash_frame.png", "text": "パンチで岩を壊せる", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_48_47_1.mp3"},
        17: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_18_06_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_18_11_2.mp3", "image": "https://storage.googleapis.com/profile_assets/4scooterframe.png", "text": "原付を乗れるようになった", "english_text": "have learned how to ride a scooter"},
        18: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_19_38_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_19_45_2.mp3", "image": "https://storage.googleapis.com/profile_assets/5treeframe.png", "text": "木を蹴り一発で破壊できる", "english_text": "can destroy "},
        19: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_05_1.mp3", "image": "https://storage.googleapis.com/profile_assets/soap_frame.png", "text": "シャボン玉攻撃できるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_49_58_1.mp3"},
        20: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_20_28_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_20_34_2.mp3", "image": "https://storage.googleapis.com/profile_assets/6animalsframe.png", "text": "動物をコントロールできるようになった", "english_text": "are able to control animals"},
        21: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_17_1.mp3", "image": "https://storage.googleapis.com/profile_assets/h-adult.png", "text": "一般的な大人です。握力５００キロ", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_57_34_1.mp3"},
        22: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_14_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_19_2.mp3", "image": "https://storage.googleapis.com/profile_assets/7motorcycleframe.png", "text": "普通のバイクを乗れるようになった", "english_text": "are able to ride a regular motorcycle"},
        23: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_44_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_21_49_2.mp3", "image": "https://storage.googleapis.com/profile_assets/8driveframe.png", "text": "車の運転をできるになった", "english_text": "are able to drive a car"},
        24: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_07_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_11_2.mp3", "image": "https://storage.googleapis.com/profile_assets/9moneyframe.png", "text": "会社作って大金持ちになった", "english_text": "made a company and became filthy rich"},
        25: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_43_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_09_23_22_50_2.mp3", "image": "https://storage.googleapis.com/profile_assets/10airplaneframe.png", "text": "飛行機を操縦できるようになった", "english_text": "have learned how to fly an airplane"},
        26: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_07_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_26_2.mp3", "image": "https://storage.googleapis.com/profile_assets/10earthquakeframe.png", "text": "自身を作る力を手に入れた", "english_text": "have gained the power to create earth quakes"},
        27: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_28_1.mp3", "image": "https://storage.googleapis.com/profile_assets/sun_frame.png", "text": "勉強の成果で小さい太陽作れるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_52_29_1.mp3"},
        28: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_41_1.mp3", "image": "https://storage.googleapis.com/profile_assets/wolf_frame.png", "text": "この可愛いペットを乗れるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_57_07_1.mp3"},
        29: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_34_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_08_38_2.mp3", "image": "https://storage.googleapis.com/profile_assets/11beardmanframe.png", "text": "髭の攻撃できるようになった", "english_text": "can attack with your beard"},
        30: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_01_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_07_2.mp3", "image": "https://storage.googleapis.com/profile_assets/12polarbearframe.png", "text": "北極熊を乗っているパラディンになった", "english_text": "are a palading riding a polar bear"},
        31: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_01_51_1.mp3", "image": "https://storage.googleapis.com/profile_assets/i-hero.png", "text": "ちょっとヒーローぽい存在", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_07_09_1.mp3"},
        32: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_10_56_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_02_2.mp3", "image": "https://storage.googleapis.com/profile_assets/13diamondframe.png", "text": "握力でダイアをつぶせるようになった", "english_text": "are able to crush a diamond with your hands"},
        33: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_22_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_27_2.mp3", "image": "https://storage.googleapis.com/profile_assets/14spacemanframe.png", "text": "宇宙飛行機を操縦できるようになった", "english_text": "are able to fly a space ship"},
        34: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_50_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_11_54_2.mp3", "image": "https://storage.googleapis.com/profile_assets/15dragonframe.png", "text": "魔法で龍を呼び出すことができる", "english_text": "are able to summon a dragon with magic"},
        35: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_02_1.mp3", "image": "https://storage.googleapis.com/profile_assets/j-lightning.png", "text": "雷の力を持つ本物のヒーロー", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_15_58_51_1.mp3"},
        36: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_21_1.mp3", "image": "https://storage.googleapis.com/profile_assets/blackhole_frame.png", "text": "勉強の成果で小さいブラックホール作れるようになった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_58_39_1.mp3"},
        37: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_33_1.mp3", "image": "https://storage.googleapis.com/profile_assets/k-lazer.png", "text": "雷とレーザーの力を持つ本物のヒーロー", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_00_03_1.mp3"},
        38: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_42_1.mp3", "image": "https://storage.googleapis.com/profile_assets/beardman_frame.png", "text": "髭生やしてさらに強くなった", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_11_59_54_1.mp3"},
        39: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_12_45_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_12_56_2.mp3", "image": "https://storage.googleapis.com/profile_assets/16moonframe.png", "text": "忍術で月を破壊できる", "english_text": "can destroy the moon with ninjutsu"},
        40: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_02_57_1.mp3", "image": "https://storage.googleapis.com/profile_assets/l-earth.png", "text": "地球を１秒で破壊できる侍", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_04_48_1.mp3"},
        41: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_13_13_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_13_21_2.mp3", "image": "https://storage.googleapis.com/profile_assets/17sunframe.png", "text": "星を団子の様に食べれる", "english_text": "can eat stars like you eat dango"},
        42: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_08_1.mp3", "image": "https://storage.googleapis.com/profile_assets/neutronstar_frame.png", "text": "普段から朝ごはんに中性子星を食べる", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_12_00_40_1.mp3"},
        43: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_14_41_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_14_51_2.mp3", "image": "https://storage.googleapis.com/profile_assets/18antimatterframe.png", "text": "反物質をつくれるようになった", "english_text": "are able to create antimatter"},
        44: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_21_1.mp3", "image": "https://storage.googleapis.com/profile_assets/blackholedrinker_frame.png", "text": "喉乾いたときブラックホールをストローで飲む", "audio": "https://storage.googleapis.com/profile_assets/2024_11_16_12_02_15_1.mp3"},
        45: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_23_48_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_23_57_2.mp3", "image": "https://storage.googleapis.com/profile_assets/19galaxyframe.png", "text": "掃除機で銀河を吸い取れる", "english_text": "you can suck in galaxies with your vacuum cleaner"},
        46: {"audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_24_21_2.mp3", "english_audio": "https://storage.googleapis.com/profile_assets/2025_09_10_13_24_31_2.mp3", "image": "https://storage.googleapis.com/profile_assets/20galaxycreatorframe.png", "text": "息するだけで銀河を作れる", "english_text": "can create galaxies by just breathing"},
        47: {"english_audio": "https://storage.googleapis.com/profile_assets/2024_12_07_19_03_31_1.mp3", "image": "https://storage.googleapis.com/profile_assets/m-universe.png", "text": "宇宙のすべてを１秒で破壊できる存在", "audio": "https://storage.googleapis.com/profile_assets/2024_10_29_16_05_21_1.mp3"},

    }
    result = {level: memories[level] for level in range(1, levels + 1) if level in memories}
    return result

def get_total_question():
    question_counts = {
        "total_japanese_questions": Question.objects.filter(test__category='japanese').count(),
        "total_english_5_questions": Question.objects.filter(test__category='english_5').count(),
        "total_english_6_questions": Question.objects.filter(test__category='english_6').count(),
        "total_jr_1_questions": Question.objects.filter(test__category='jr_1').count(),
        "total_jr_2_questions": Question.objects.filter(test__category='jr_2').count(),
        "total_jr_3_questions": Question.objects.filter(test__category='jr_3').count(),
        "total_phonics_questions": Question.objects.filter(test__category='phonics').count(),
        "total_numbers_questions": Question.objects.filter(test__category='numbers').count(),
    }
    return question_counts

def get_total_questions():
    question_counts = {
        "total_japanese_questions": Test.objects.filter(category='japanese').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_english_5_questions": Test.objects.filter(category='english_5').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_english_6_questions": Test.objects.filter(category='english_6').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_jr_1_questions": Test.objects.filter(category='jr_1').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_jr_2_questions": Test.objects.filter(category='jr_2').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_jr_3_questions": Test.objects.filter(category='jr_3').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_phonics_questions": Test.objects.filter(category='phonics').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_numbers_questions": Test.objects.filter(category='numbers').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_eiken_questions": Test.objects.filter(category='eiken').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_eiken4_questions": Test.objects.filter(category='eiken4').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_eiken3_questions": Test.objects.filter(category='eiken3').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_eiken_pre2_questions": Test.objects.filter(category='eiken_pre2').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
        "total_eiken2_questions": Test.objects.filter(category='eiken2').aggregate(total_score=Sum('total_score'))['total_score'] or 0,
    }
    return question_counts





def get_total_category_scores(user):
    total_category_scores = {
        "total_japanese_scores": MaxScore.objects.filter(user=user, test__category='japanese').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_english_5_scores": MaxScore.objects.filter(user=user, test__category='english_5').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_english_6_scores": MaxScore.objects.filter(user=user, test__category='english_6').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_jr_1_scores": MaxScore.objects.filter(user=user, test__category='jr_1').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_jr_2_scores": MaxScore.objects.filter(user=user, test__category='jr_2').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_jr_3_scores": MaxScore.objects.filter(user=user, test__category='jr_3').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_phonics_scores": MaxScore.objects.filter(user=user, test__category='phonics').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_numbers_scores": MaxScore.objects.filter(user=user, test__category='numbers').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_eiken_scores": MaxScore.objects.filter(user=user, test__category='eiken').aggregate(total_score=Sum('score'))['total_score'] or 0,
        "total_eiken4_scores": MaxScore.objects.filter(user=user, test__category='eiken4').aggregate(total_score=Sum('score'))['total_score'] or 0,
    }
    return total_category_scores