# Generated by Django 5.1.6 on 2025-09-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
