# Generated by Django 5.1.6 on 2025-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0002_club_picture_lesson_picture_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
