# Generated by Django 5.1.6 on 2025-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0003_alter_club_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='search_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='subdomain',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
