# Generated by Django 5.1.6 on 2025-10-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0004_club_search_description_club_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('level_counts', models.JSONField(default=dict)),
                ('last_participation_date', models.DateField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='kaibaru.lesson')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='kaibaru.member')),
            ],
            options={
                'unique_together': {('member', 'lesson')},
            },
        ),
    ]
