# Generated by Django 5.1.6 on 2025-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0006_remove_club_members_member_club_alter_member_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='kaibaru.member'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
    ]
