# Generated by Django 5.1.6 on 2025-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0008_remove_club_members_member_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='second_last_participation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
