# Generated by Django 5.1.6 on 2025-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0009_participation_second_last_participation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='line_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/line_qr/'),
        ),
    ]
