# Generated by Django 5.1.6 on 2025-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0010_club_facebook_url_club_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='line_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
