# Generated by Django 5.1.6 on 2025-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0011_alter_club_line_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
