# Generated by Django 5.1.6 on 2025-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0012_member_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='line_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='line/'),
        ),
    ]
