# Generated by Django 5.1.6 on 2025-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0013_alter_club_line_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='line_add_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
