# Generated by Django 5.1.6 on 2025-10-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0014_club_line_add_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='line_add_url',
            new_name='line_url',
        ),
    ]
