# Generated by Django 5.1.6 on 2025-10-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0015_rename_line_add_url_club_line_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=200)),
                ('height', models.FloatField(default=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_images', to='kaibaru.club')),
            ],
        ),
    ]
