# Generated by Django 5.1.6 on 2025-10-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0016_homeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='home',
        ),
    ]
