# Generated by Django 5.1.6 on 2025-10-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0017_remove_club_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='home',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
