# Generated by Django 5.1.6 on 2025-11-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0018_club_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='width',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='x',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='y',
        ),
    ]
