# Generated by Django 5.1.6 on 2025-11-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0019_remove_homeimage_height_remove_homeimage_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='height',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='width',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
