# Generated by Django 5.1.6 on 2025-11-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0020_homeimage_height_homeimage_width_homeimage_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='width',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='x',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='y',
        ),
    ]
