# Generated by Django 5.1.6 on 2025-11-02 01:21

import kaibaru.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0021_remove_homeimage_height_remove_homeimage_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=kaibaru.storage_backends.PrivateMediaStorage(), upload_to='members/'),
        ),
    ]
