# Generated by Django 5.1.6 on 2025-11-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0022_alter_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lessons'),
        ),
    ]
