# Generated by Django 5.1.6 on 2025-11-02 02:08

import kaibaru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0023_alter_lesson_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_lessons_upload_to),
        ),
    ]
