# Generated by Django 5.1.6 on 2025-11-08 03:11

import django.db.models.deletion
import kaibaru.models
import kaibaru.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0024_alter_lesson_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='line_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.line_qr_upload_to),
        ),
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_picture_upload_to),
        ),
        migrations.AlterField(
            model_name='club',
            name='system',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='trial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=kaibaru.storage_backends.PrivateMediaStorage(), upload_to=kaibaru.models.club_member_pictures_upload_to),
        ),
        migrations.CreateModel(
            name='SlateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=kaibaru.models.club_slate_image_upload_to)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slate_image', to='kaibaru.club')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
