# Generated by Django 5.1.6 on 2025-11-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0025_alter_club_contact_alter_club_line_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateimage',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('trial', 'Trial'), ('system', 'System'), ('contact', 'Contact')], default='home', max_length=20),
        ),
    ]
