# Generated by Django 5.1.6 on 2025-11-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0026_slateimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateimage',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slate_images', to='kaibaru.club'),
        ),
    ]
