# Generated by Django 5.1.6 on 2025-11-17 04:38

import kaibaru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0027_alter_slateimage_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_favicon_upload_to),
        ),
        migrations.AddField(
            model_name='club',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_og_image_upload_to),
        ),
        migrations.AddField(
            model_name='club',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
