# Generated by Django 5.1.6 on 2025-11-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0028_club_favicon_club_og_image_club_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
    ]
