# Generated by Django 5.1.6 on 2025-11-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0029_remove_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='join_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
