# Generated by Django 5.1.6 on 2025-11-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0030_club_join_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='has_levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='level_milestones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='level_names',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
