# Generated by Django 5.1.6 on 2025-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0031_club_has_levels_club_level_milestones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='manual_level_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='member',
            name='manual_total_participation',
            field=models.IntegerField(default=0),
        ),
    ]
