# Generated by Django 5.1.6 on 2025-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0032_member_manual_level_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='has_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
