# Generated by Django 5.1.6 on 2025-12-01 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0033_club_has_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 16, 0)),
        ),
    ]
