# Generated by Django 5.1.6 on 2025-12-01 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0034_lesson_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 7, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
