# Generated by Django 5.1.6 on 2025-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0035_alter_lesson_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
