# Generated by Django 5.1.6 on 2025-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0036_alter_lesson_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
