# Generated by Django 5.1.6 on 2025-12-02 02:38

import kaibaru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0037_club_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_member_pictures_upload_to),
        ),
    ]
