# Generated by Django 5.1.6 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0038_alter_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='participation_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
