# Generated by Django 5.1.6 on 2025-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0039_member_participation_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='furigana',
            field=models.CharField(default='', max_length=200),
        ),
    ]
