# Generated by Django 5.1.6 on 2025-12-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0041_member_expiration_date_member_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='trial_start_date',
        ),
        migrations.AddField(
            model_name='club',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
