# Generated by Django 5.1.6 on 2025-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0042_remove_member_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_kyukai',
            field=models.BooleanField(default=False),
        ),
    ]
