# Generated by Django 5.1.6 on 2025-12-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0043_member_is_kyukai'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kyukai_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
