# Generated by Django 5.1.6 on 2025-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0044_member_kyukai_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='frozen_deleted_unpaid_members',
            field=models.IntegerField(default=0),
        ),
    ]
