# Generated by Django 5.1.6 on 2025-12-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0045_club_frozen_deleted_unpaid_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_kyukai_paid',
            field=models.BooleanField(default=False),
        ),
    ]
