# Generated by Django 5.1.6 on 2025-12-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0046_member_is_kyukai_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='frozen_deleted_unpaid_members',
            new_name='deleted_unpaid_members',
        ),
    ]
