# Generated by Django 5.1.6 on 2025-12-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0047_rename_frozen_deleted_unpaid_members_club_deleted_unpaid_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='deleted_unpaid_members',
        ),
    ]
