# Generated by Django 5.1.6 on 2025-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0048_remove_club_deleted_unpaid_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_paid_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
