# Generated by Django 5.1.6 on 2025-12-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0049_club_last_paid_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
