# Generated by Django 5.1.6 on 2026-01-06 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0052_club_stripe_account_id_club_stripe_charges_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slateimage',
            name='category',
        ),
        migrations.AddField(
            model_name='slateimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
