# Generated by Django 5.1.6 on 2026-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0053_remove_slateimage_category_slateimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateimage',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
