# Generated by Django 5.1.6 on 2026-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0054_slateimage_hash'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slateimage',
            constraint=models.UniqueConstraint(fields=('club', 'hash'), name='unique_slate_image_per_club_hash'),
        ),
    ]
