# Generated by Django 5.1.6 on 2025-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_jr_1_score',
            field=models.FloatField(default=0.0),
        ),
    ]
