# Generated by Django 5.1.6 on 2025-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_total_jr_1_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_4eiken_score',
            field=models.FloatField(default=0.0),
        ),
    ]
