# Generated by Django 5.1.6 on 2025-05-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_total_4eiken_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='total_4eiken_score',
            new_name='total_eiken4_score',
        ),
    ]
