# Generated by Django 5.1.6 on 2025-05-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_total_eiken4_score_customuser_total_4eiken_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_eiken2_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_eiken3_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_eiken_pre2_score',
            field=models.FloatField(default=0.0),
        ),
    ]
