# Generated by Django 5.1.6 on 2025-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_total_eiken2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_jr_2_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_jr_3_score',
            field=models.FloatField(default=0.0),
        ),
    ]
