# Generated by Django 5.1.6 on 2025-02-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_name_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
