# Generated by Django 5.1.6 on 2025-03-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_name_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomrequest',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.classroom'),
        ),
    ]
