# Generated by Django 5.1.6 on 2025-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_classroomrequest_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creator_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
