# Generated by Django 5.1.6 on 2025-03-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='creator_id',
        ),
    ]
