# Generated by Django 5.1.6 on 2025-03-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_test_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
