# Generated by Django 5.1.6 on 2025-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='finals',
            field=models.BooleanField(default=False),
        ),
    ]
