# Generated by Django 5.1.6 on 2025-03-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_test_finals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='finals',
        ),
    ]
