# Generated by Django 5.1.6 on 2025-04-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_test_finals'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='battle_permission',
            field=models.BooleanField(default=False),
        ),
    ]
