# Generated by Django 5.1.6 on 2025-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_question_display_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='ivar_voice',
            field=models.BooleanField(default=False),
        ),
    ]
