# Generated by Django 5.1.6 on 2025-05-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_classroom_ivar_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('japanese', 'Japanese'), ('english_5', 'English 5'), ('english_6', 'English 6'), ('jr_1', 'jr_1'), ('jr_2', 'jr_2'), ('jr_3', 'jr_3'), ('phonics', 'Phonics'), ('numbers', 'Numbers'), ('eiken', 'Eiken')], default='phonics', max_length=20),
        ),
    ]
