# Generated by Django 5.1.6 on 2025-05-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sentence_order',
            field=models.BooleanField(default=False),
        ),
    ]
