# Generated by Django 5.1.6 on 2025-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('ar', 'Ar')], default='a', max_length=20),
        ),
    ]
