# Generated by Django 5.1.6 on 2025-08-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='question_category',
        ),
    ]
