# Generated by Django 5.1.6 on 2025-08-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_category_question_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_category',
            new_name='category',
        ),
    ]
