# Generated by Django 5.1.6 on 2025-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_question_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name_b',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name_c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
