# Generated by Django 5.1.6 on 2025-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_test_name_ar_test_name_b_test_name_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='story_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='story_sound_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
