# Generated by Django 5.1.6 on 2025-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_question_story_question_story_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='full_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='full_story_sound_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
